// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/v1alpha1/capsule_service.proto

package v1alpha1pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapsuleService_Create_FullMethodName = "/falak.api.v1alpha1.CapsuleService/Create"
	CapsuleService_Get_FullMethodName    = "/falak.api.v1alpha1.CapsuleService/Get"
	CapsuleService_List_FullMethodName   = "/falak.api.v1alpha1.CapsuleService/List"
	CapsuleService_Update_FullMethodName = "/falak.api.v1alpha1.CapsuleService/Update"
	CapsuleService_Delete_FullMethodName = "/falak.api.v1alpha1.CapsuleService/Delete"
	CapsuleService_Watch_FullMethodName  = "/falak.api.v1alpha1.CapsuleService/Watch"
	CapsuleService_Logs_FullMethodName   = "/falak.api.v1alpha1.CapsuleService/Logs"
)

// CapsuleServiceClient is the client API for CapsuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CapsuleService manages capsule lifecycle via the Falak API.
type CapsuleServiceClient interface {
	// Create deploys a new capsule to the mesh.
	Create(ctx context.Context, in *CreateCapsuleRequest, opts ...grpc.CallOption) (*CapsuleResource, error)
	// Get returns a single capsule by ID.
	Get(ctx context.Context, in *GetCapsuleRequest, opts ...grpc.CallOption) (*CapsuleResource, error)
	// List returns capsules matching the filter criteria.
	List(ctx context.Context, in *ListCapsulesRequest, opts ...grpc.CallOption) (*ListCapsulesResponse, error)
	// Update modifies an existing capsule's spec.
	Update(ctx context.Context, in *UpdateCapsuleRequest, opts ...grpc.CallOption) (*CapsuleResource, error)
	// Delete removes a capsule from the mesh.
	Delete(ctx context.Context, in *DeleteCapsuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Watch streams capsule events in real time.
	Watch(ctx context.Context, in *WatchCapsulesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	// Logs streams container logs from the node running the capsule.
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
}

type capsuleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapsuleServiceClient(cc grpc.ClientConnInterface) CapsuleServiceClient {
	return &capsuleServiceClient{cc}
}

func (c *capsuleServiceClient) Create(ctx context.Context, in *CreateCapsuleRequest, opts ...grpc.CallOption) (*CapsuleResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapsuleResource)
	err := c.cc.Invoke(ctx, CapsuleService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capsuleServiceClient) Get(ctx context.Context, in *GetCapsuleRequest, opts ...grpc.CallOption) (*CapsuleResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapsuleResource)
	err := c.cc.Invoke(ctx, CapsuleService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capsuleServiceClient) List(ctx context.Context, in *ListCapsulesRequest, opts ...grpc.CallOption) (*ListCapsulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCapsulesResponse)
	err := c.cc.Invoke(ctx, CapsuleService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capsuleServiceClient) Update(ctx context.Context, in *UpdateCapsuleRequest, opts ...grpc.CallOption) (*CapsuleResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapsuleResource)
	err := c.cc.Invoke(ctx, CapsuleService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capsuleServiceClient) Delete(ctx context.Context, in *DeleteCapsuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CapsuleService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capsuleServiceClient) Watch(ctx context.Context, in *WatchCapsulesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CapsuleService_ServiceDesc.Streams[0], CapsuleService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchCapsulesRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CapsuleService_WatchClient = grpc.ServerStreamingClient[WatchEvent]

func (c *capsuleServiceClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CapsuleService_ServiceDesc.Streams[1], CapsuleService_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CapsuleService_LogsClient = grpc.ServerStreamingClient[LogEntry]

// CapsuleServiceServer is the server API for CapsuleService service.
// All implementations must embed UnimplementedCapsuleServiceServer
// for forward compatibility.
//
// CapsuleService manages capsule lifecycle via the Falak API.
type CapsuleServiceServer interface {
	// Create deploys a new capsule to the mesh.
	Create(context.Context, *CreateCapsuleRequest) (*CapsuleResource, error)
	// Get returns a single capsule by ID.
	Get(context.Context, *GetCapsuleRequest) (*CapsuleResource, error)
	// List returns capsules matching the filter criteria.
	List(context.Context, *ListCapsulesRequest) (*ListCapsulesResponse, error)
	// Update modifies an existing capsule's spec.
	Update(context.Context, *UpdateCapsuleRequest) (*CapsuleResource, error)
	// Delete removes a capsule from the mesh.
	Delete(context.Context, *DeleteCapsuleRequest) (*emptypb.Empty, error)
	// Watch streams capsule events in real time.
	Watch(*WatchCapsulesRequest, grpc.ServerStreamingServer[WatchEvent]) error
	// Logs streams container logs from the node running the capsule.
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	mustEmbedUnimplementedCapsuleServiceServer()
}

// UnimplementedCapsuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapsuleServiceServer struct{}

func (UnimplementedCapsuleServiceServer) Create(context.Context, *CreateCapsuleRequest) (*CapsuleResource, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCapsuleServiceServer) Get(context.Context, *GetCapsuleRequest) (*CapsuleResource, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCapsuleServiceServer) List(context.Context, *ListCapsulesRequest) (*ListCapsulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCapsuleServiceServer) Update(context.Context, *UpdateCapsuleRequest) (*CapsuleResource, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCapsuleServiceServer) Delete(context.Context, *DeleteCapsuleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCapsuleServiceServer) Watch(*WatchCapsulesRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedCapsuleServiceServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedCapsuleServiceServer) mustEmbedUnimplementedCapsuleServiceServer() {}
func (UnimplementedCapsuleServiceServer) testEmbeddedByValue()                        {}

// UnsafeCapsuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapsuleServiceServer will
// result in compilation errors.
type UnsafeCapsuleServiceServer interface {
	mustEmbedUnimplementedCapsuleServiceServer()
}

func RegisterCapsuleServiceServer(s grpc.ServiceRegistrar, srv CapsuleServiceServer) {
	// If the following call panics, it indicates UnimplementedCapsuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapsuleService_ServiceDesc, srv)
}

func _CapsuleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCapsuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapsuleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapsuleService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapsuleServiceServer).Create(ctx, req.(*CreateCapsuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapsuleService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapsuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapsuleServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapsuleService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapsuleServiceServer).Get(ctx, req.(*GetCapsuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapsuleService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCapsulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapsuleServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapsuleService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapsuleServiceServer).List(ctx, req.(*ListCapsulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapsuleService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCapsuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapsuleServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapsuleService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapsuleServiceServer).Update(ctx, req.(*UpdateCapsuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapsuleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCapsuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapsuleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapsuleService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapsuleServiceServer).Delete(ctx, req.(*DeleteCapsuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapsuleService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchCapsulesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CapsuleServiceServer).Watch(m, &grpc.GenericServerStream[WatchCapsulesRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CapsuleService_WatchServer = grpc.ServerStreamingServer[WatchEvent]

func _CapsuleService_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CapsuleServiceServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CapsuleService_LogsServer = grpc.ServerStreamingServer[LogEntry]

// CapsuleService_ServiceDesc is the grpc.ServiceDesc for CapsuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapsuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "falak.api.v1alpha1.CapsuleService",
	HandlerType: (*CapsuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CapsuleService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CapsuleService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CapsuleService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CapsuleService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CapsuleService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _CapsuleService_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Logs",
			Handler:       _CapsuleService_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/v1alpha1/capsule_service.proto",
}
