// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1alpha1/capsule_service.proto

package v1alpha1pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapsuleResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ObjectMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Spec          *CapsuleSpec           `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *CapsuleStatus         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapsuleResource) Reset() {
	*x = CapsuleResource{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapsuleResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleResource) ProtoMessage() {}

func (x *CapsuleResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleResource.ProtoReflect.Descriptor instead.
func (*CapsuleResource) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{0}
}

func (x *CapsuleResource) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CapsuleResource) GetSpec() *CapsuleSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CapsuleResource) GetStatus() *CapsuleStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type CapsuleSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	ImageDigest   string                 `protobuf:"bytes,2,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	Orbit         string                 `protobuf:"bytes,3,opt,name=orbit,proto3" json:"orbit,omitempty"`
	Tier          string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	CpuCores      int32                  `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuCoresMax   int32                  `protobuf:"varint,6,opt,name=cpu_cores_max,json=cpuCoresMax,proto3" json:"cpu_cores_max,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,7,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	MemoryMbMax   int64                  `protobuf:"varint,8,opt,name=memory_mb_max,json=memoryMbMax,proto3" json:"memory_mb_max,omitempty"`
	DiskMb        int64                  `protobuf:"varint,9,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	ReplicasMin   int32                  `protobuf:"varint,10,opt,name=replicas_min,json=replicasMin,proto3" json:"replicas_min,omitempty"`
	ReplicasMax   int32                  `protobuf:"varint,11,opt,name=replicas_max,json=replicasMax,proto3" json:"replicas_max,omitempty"`
	ReplicasExact int32                  `protobuf:"varint,12,opt,name=replicas_exact,json=replicasExact,proto3" json:"replicas_exact,omitempty"`
	Env           map[string]string      `protobuf:"bytes,13,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command       []string               `protobuf:"bytes,14,rep,name=command,proto3" json:"command,omitempty"`
	NetworkMode   string                 `protobuf:"bytes,15,opt,name=network_mode,json=networkMode,proto3" json:"network_mode,omitempty"`
	Ports         []*PortMapping         `protobuf:"bytes,16,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapsuleSpec) Reset() {
	*x = CapsuleSpec{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapsuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleSpec) ProtoMessage() {}

func (x *CapsuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleSpec.ProtoReflect.Descriptor instead.
func (*CapsuleSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{1}
}

func (x *CapsuleSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CapsuleSpec) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *CapsuleSpec) GetOrbit() string {
	if x != nil {
		return x.Orbit
	}
	return ""
}

func (x *CapsuleSpec) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *CapsuleSpec) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *CapsuleSpec) GetCpuCoresMax() int32 {
	if x != nil {
		return x.CpuCoresMax
	}
	return 0
}

func (x *CapsuleSpec) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CapsuleSpec) GetMemoryMbMax() int64 {
	if x != nil {
		return x.MemoryMbMax
	}
	return 0
}

func (x *CapsuleSpec) GetDiskMb() int64 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

func (x *CapsuleSpec) GetReplicasMin() int32 {
	if x != nil {
		return x.ReplicasMin
	}
	return 0
}

func (x *CapsuleSpec) GetReplicasMax() int32 {
	if x != nil {
		return x.ReplicasMax
	}
	return 0
}

func (x *CapsuleSpec) GetReplicasExact() int32 {
	if x != nil {
		return x.ReplicasExact
	}
	return 0
}

func (x *CapsuleSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CapsuleSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CapsuleSpec) GetNetworkMode() string {
	if x != nil {
		return x.NetworkMode
	}
	return ""
}

func (x *CapsuleSpec) GetPorts() []*PortMapping {
	if x != nil {
		return x.Ports
	}
	return nil
}

// PortMapping mirrors capsule.PortMapping so the API can carry the
// container port spec from a CUE file through to the runtime layer.
// host=0 lets Podman pick a free host port at start.
type PortMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Container     int32                  `protobuf:"varint,2,opt,name=container,proto3" json:"container,omitempty"`
	Host          int32                  `protobuf:"varint,3,opt,name=host,proto3" json:"host,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"` // "tcp" (default) or "udp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortMapping) Reset() {
	*x = PortMapping{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMapping) ProtoMessage() {}

func (x *PortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMapping.ProtoReflect.Descriptor instead.
func (*PortMapping) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{2}
}

func (x *PortMapping) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PortMapping) GetContainer() int32 {
	if x != nil {
		return x.Container
	}
	return 0
}

func (x *PortMapping) GetHost() int32 {
	if x != nil {
		return x.Host
	}
	return 0
}

func (x *PortMapping) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type CapsuleStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Replicas      []*ReplicaStatus       `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapsuleStatus) Reset() {
	*x = CapsuleStatus{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapsuleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleStatus) ProtoMessage() {}

func (x *CapsuleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleStatus.ProtoReflect.Descriptor instead.
func (*CapsuleStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{3}
}

func (x *CapsuleStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CapsuleStatus) GetReplicas() []*ReplicaStatus {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type ReplicaStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Ports         []*PortMapping         `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"` // RESOLVED host-port bindings (actual host ports, incl. auto allocations)
	Ip            string                 `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`       // resolved container IP (bridge mode); empty for host
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaStatus) Reset() {
	*x = ReplicaStatus{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaStatus) ProtoMessage() {}

func (x *ReplicaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaStatus.ProtoReflect.Descriptor instead.
func (*ReplicaStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicaStatus) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ReplicaStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReplicaStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReplicaStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ReplicaStatus) GetPorts() []*PortMapping {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ReplicaStatus) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type CreateCapsuleRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Cluster          string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image            string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Orbit            string                 `protobuf:"bytes,4,opt,name=orbit,proto3" json:"orbit,omitempty"`
	Tier             string                 `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`
	Labels           map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CpuCores         int32                  `protobuf:"varint,7,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuCoresMax      int32                  `protobuf:"varint,8,opt,name=cpu_cores_max,json=cpuCoresMax,proto3" json:"cpu_cores_max,omitempty"`
	MemoryMb         int64                  `protobuf:"varint,9,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	MemoryMbMax      int64                  `protobuf:"varint,10,opt,name=memory_mb_max,json=memoryMbMax,proto3" json:"memory_mb_max,omitempty"`
	DiskMb           int64                  `protobuf:"varint,11,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	ReplicasMin      int32                  `protobuf:"varint,12,opt,name=replicas_min,json=replicasMin,proto3" json:"replicas_min,omitempty"`
	ReplicasMax      int32                  `protobuf:"varint,13,opt,name=replicas_max,json=replicasMax,proto3" json:"replicas_max,omitempty"`
	ReplicasExact    int32                  `protobuf:"varint,14,opt,name=replicas_exact,json=replicasExact,proto3" json:"replicas_exact,omitempty"`
	Env              map[string]string      `protobuf:"bytes,15,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command          []string               `protobuf:"bytes,16,rep,name=command,proto3" json:"command,omitempty"`
	NetworkMode      string                 `protobuf:"bytes,17,opt,name=network_mode,json=networkMode,proto3" json:"network_mode,omitempty"`
	ImageDigest      string                 `protobuf:"bytes,18,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	RegistryUrl      string                 `protobuf:"bytes,19,opt,name=registry_url,json=registryUrl,proto3" json:"registry_url,omitempty"`
	RegistryUsername string                 `protobuf:"bytes,20,opt,name=registry_username,json=registryUsername,proto3" json:"registry_username,omitempty"`
	RegistryPassword string                 `protobuf:"bytes,21,opt,name=registry_password,json=registryPassword,proto3" json:"registry_password,omitempty"`
	Ports            []*PortMapping         `protobuf:"bytes,22,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCapsuleRequest) Reset() {
	*x = CreateCapsuleRequest{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCapsuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCapsuleRequest) ProtoMessage() {}

func (x *CreateCapsuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCapsuleRequest.ProtoReflect.Descriptor instead.
func (*CreateCapsuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCapsuleRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *CreateCapsuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCapsuleRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateCapsuleRequest) GetOrbit() string {
	if x != nil {
		return x.Orbit
	}
	return ""
}

func (x *CreateCapsuleRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *CreateCapsuleRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateCapsuleRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *CreateCapsuleRequest) GetCpuCoresMax() int32 {
	if x != nil {
		return x.CpuCoresMax
	}
	return 0
}

func (x *CreateCapsuleRequest) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CreateCapsuleRequest) GetMemoryMbMax() int64 {
	if x != nil {
		return x.MemoryMbMax
	}
	return 0
}

func (x *CreateCapsuleRequest) GetDiskMb() int64 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

func (x *CreateCapsuleRequest) GetReplicasMin() int32 {
	if x != nil {
		return x.ReplicasMin
	}
	return 0
}

func (x *CreateCapsuleRequest) GetReplicasMax() int32 {
	if x != nil {
		return x.ReplicasMax
	}
	return 0
}

func (x *CreateCapsuleRequest) GetReplicasExact() int32 {
	if x != nil {
		return x.ReplicasExact
	}
	return 0
}

func (x *CreateCapsuleRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateCapsuleRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CreateCapsuleRequest) GetNetworkMode() string {
	if x != nil {
		return x.NetworkMode
	}
	return ""
}

func (x *CreateCapsuleRequest) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *CreateCapsuleRequest) GetRegistryUrl() string {
	if x != nil {
		return x.RegistryUrl
	}
	return ""
}

func (x *CreateCapsuleRequest) GetRegistryUsername() string {
	if x != nil {
		return x.RegistryUsername
	}
	return ""
}

func (x *CreateCapsuleRequest) GetRegistryPassword() string {
	if x != nil {
		return x.RegistryPassword
	}
	return ""
}

func (x *CreateCapsuleRequest) GetPorts() []*PortMapping {
	if x != nil {
		return x.Ports
	}
	return nil
}

type GetCapsuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapsuleRequest) Reset() {
	*x = GetCapsuleRequest{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapsuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapsuleRequest) ProtoMessage() {}

func (x *GetCapsuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapsuleRequest.ProtoReflect.Descriptor instead.
func (*GetCapsuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetCapsuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCapsuleRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

type ListCapsulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Orbit         string                 `protobuf:"bytes,3,opt,name=orbit,proto3" json:"orbit,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapsulesRequest) Reset() {
	*x = ListCapsulesRequest{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapsulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapsulesRequest) ProtoMessage() {}

func (x *ListCapsulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapsulesRequest.ProtoReflect.Descriptor instead.
func (*ListCapsulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListCapsulesRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ListCapsulesRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListCapsulesRequest) GetOrbit() string {
	if x != nil {
		return x.Orbit
	}
	return ""
}

func (x *ListCapsulesRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListCapsulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capsules      []*CapsuleResource     `protobuf:"bytes,1,rep,name=capsules,proto3" json:"capsules,omitempty"`
	Paging        *PagedResult           `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapsulesResponse) Reset() {
	*x = ListCapsulesResponse{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapsulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapsulesResponse) ProtoMessage() {}

func (x *ListCapsulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapsulesResponse.ProtoReflect.Descriptor instead.
func (*ListCapsulesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListCapsulesResponse) GetCapsules() []*CapsuleResource {
	if x != nil {
		return x.Capsules
	}
	return nil
}

func (x *ListCapsulesResponse) GetPaging() *PagedResult {
	if x != nil {
		return x.Paging
	}
	return nil
}

type UpdateCapsuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command       []string               `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCapsuleRequest) Reset() {
	*x = UpdateCapsuleRequest{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCapsuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCapsuleRequest) ProtoMessage() {}

func (x *UpdateCapsuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCapsuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateCapsuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCapsuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCapsuleRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *UpdateCapsuleRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UpdateCapsuleRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *UpdateCapsuleRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type DeleteCapsuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCapsuleRequest) Reset() {
	*x = DeleteCapsuleRequest{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCapsuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCapsuleRequest) ProtoMessage() {}

func (x *DeleteCapsuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCapsuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteCapsuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCapsuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteCapsuleRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

type WatchCapsulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCapsulesRequest) Reset() {
	*x = WatchCapsulesRequest{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCapsulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCapsulesRequest) ProtoMessage() {}

func (x *WatchCapsulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCapsulesRequest.ProtoReflect.Descriptor instead.
func (*WatchCapsulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{11}
}

func (x *WatchCapsulesRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *WatchCapsulesRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	ReplicaId     string                 `protobuf:"bytes,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	Tail          int32                  `protobuf:"varint,4,opt,name=tail,proto3" json:"tail,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{12}
}

func (x *LogsRequest) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *LogsRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

func (x *LogsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"` // "stdout" or "stderr"
	Line          string                 `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_capsule_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP(), []int{13}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_api_proto_v1alpha1_capsule_service_proto protoreflect.FileDescriptor

const file_api_proto_v1alpha1_capsule_service_proto_rawDesc = "" +
	"\n" +
	"(api/proto/v1alpha1/capsule_service.proto\x12\x12falak.api.v1alpha1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fapi/proto/v1alpha1/common.proto\"\xb5\x01\n" +
	"\x0fCapsuleResource\x122\n" +
	"\x04meta\x18\x01 \x01(\v2\x1e.falak.api.v1alpha1.ObjectMetaR\x04meta\x123\n" +
	"\x04spec\x18\x02 \x01(\v2\x1f.falak.api.v1alpha1.CapsuleSpecR\x04spec\x129\n" +
	"\x06status\x18\x03 \x01(\v2!.falak.api.v1alpha1.CapsuleStatusR\x06status\"\xe0\x04\n" +
	"\vCapsuleSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x02 \x01(\tR\vimageDigest\x12\x14\n" +
	"\x05orbit\x18\x03 \x01(\tR\x05orbit\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\x05R\bcpuCores\x12\"\n" +
	"\rcpu_cores_max\x18\x06 \x01(\x05R\vcpuCoresMax\x12\x1b\n" +
	"\tmemory_mb\x18\a \x01(\x03R\bmemoryMb\x12\"\n" +
	"\rmemory_mb_max\x18\b \x01(\x03R\vmemoryMbMax\x12\x17\n" +
	"\adisk_mb\x18\t \x01(\x03R\x06diskMb\x12!\n" +
	"\freplicas_min\x18\n" +
	" \x01(\x05R\vreplicasMin\x12!\n" +
	"\freplicas_max\x18\v \x01(\x05R\vreplicasMax\x12%\n" +
	"\x0ereplicas_exact\x18\f \x01(\x05R\rreplicasExact\x12:\n" +
	"\x03env\x18\r \x03(\v2(.falak.api.v1alpha1.CapsuleSpec.EnvEntryR\x03env\x12\x18\n" +
	"\acommand\x18\x0e \x03(\tR\acommand\x12!\n" +
	"\fnetwork_mode\x18\x0f \x01(\tR\vnetworkMode\x125\n" +
	"\x05ports\x18\x10 \x03(\v2\x1f.falak.api.v1alpha1.PortMappingR\x05ports\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\vPortMapping\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\x05R\tcontainer\x12\x12\n" +
	"\x04host\x18\x03 \x01(\x05R\x04host\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"f\n" +
	"\rCapsuleStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12=\n" +
	"\breplicas\x18\x02 \x03(\v2!.falak.api.v1alpha1.ReplicaStatusR\breplicas\"\xe1\x01\n" +
	"\rReplicaStatus\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\x05ports\x18\x05 \x03(\v2\x1f.falak.api.v1alpha1.PortMappingR\x05ports\x12\x0e\n" +
	"\x02ip\x18\x06 \x01(\tR\x02ip\"\xa6\a\n" +
	"\x14CreateCapsuleRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05orbit\x18\x04 \x01(\tR\x05orbit\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\tR\x04tier\x12L\n" +
	"\x06labels\x18\x06 \x03(\v24.falak.api.v1alpha1.CreateCapsuleRequest.LabelsEntryR\x06labels\x12\x1b\n" +
	"\tcpu_cores\x18\a \x01(\x05R\bcpuCores\x12\"\n" +
	"\rcpu_cores_max\x18\b \x01(\x05R\vcpuCoresMax\x12\x1b\n" +
	"\tmemory_mb\x18\t \x01(\x03R\bmemoryMb\x12\"\n" +
	"\rmemory_mb_max\x18\n" +
	" \x01(\x03R\vmemoryMbMax\x12\x17\n" +
	"\adisk_mb\x18\v \x01(\x03R\x06diskMb\x12!\n" +
	"\freplicas_min\x18\f \x01(\x05R\vreplicasMin\x12!\n" +
	"\freplicas_max\x18\r \x01(\x05R\vreplicasMax\x12%\n" +
	"\x0ereplicas_exact\x18\x0e \x01(\x05R\rreplicasExact\x12C\n" +
	"\x03env\x18\x0f \x03(\v21.falak.api.v1alpha1.CreateCapsuleRequest.EnvEntryR\x03env\x12\x18\n" +
	"\acommand\x18\x10 \x03(\tR\acommand\x12!\n" +
	"\fnetwork_mode\x18\x11 \x01(\tR\vnetworkMode\x12!\n" +
	"\fimage_digest\x18\x12 \x01(\tR\vimageDigest\x12!\n" +
	"\fregistry_url\x18\x13 \x01(\tR\vregistryUrl\x12+\n" +
	"\x11registry_username\x18\x14 \x01(\tR\x10registryUsername\x12+\n" +
	"\x11registry_password\x18\x15 \x01(\tR\x10registryPassword\x125\n" +
	"\x05ports\x18\x16 \x03(\v2\x1f.falak.api.v1alpha1.PortMappingR\x05ports\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x11GetCapsuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\"\x8d\x02\n" +
	"\x13ListCapsulesRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12K\n" +
	"\x06labels\x18\x02 \x03(\v23.falak.api.v1alpha1.ListCapsulesRequest.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05orbit\x18\x03 \x01(\tR\x05orbit\x12>\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1e.falak.api.v1alpha1.PaginationR\n" +
	"pagination\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x14ListCapsulesResponse\x12?\n" +
	"\bcapsules\x18\x01 \x03(\v2#.falak.api.v1alpha1.CapsuleResourceR\bcapsules\x127\n" +
	"\x06paging\x18\x02 \x01(\v2\x1f.falak.api.v1alpha1.PagedResultR\x06paging\"\xed\x01\n" +
	"\x14UpdateCapsuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12C\n" +
	"\x03env\x18\x04 \x03(\v21.falak.api.v1alpha1.UpdateCapsuleRequest.EnvEntryR\x03env\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x14DeleteCapsuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\"\xb9\x01\n" +
	"\x14WatchCapsulesRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12L\n" +
	"\x06labels\x18\x02 \x03(\v24.falak.api.v1alpha1.WatchCapsulesRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\vLogsRequest\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\tR\treplicaId\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12\x12\n" +
	"\x04tail\x18\x04 \x01(\x05R\x04tail\x120\n" +
	"\x05since\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"p\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x12\n" +
	"\x04line\x18\x03 \x01(\tR\x04line2\xa9\x06\n" +
	"\x0eCapsuleService\x12v\n" +
	"\x06Create\x12(.falak.api.v1alpha1.CreateCapsuleRequest\x1a#.falak.api.v1alpha1.CapsuleResource\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1alpha1/capsules\x12r\n" +
	"\x03Get\x12%.falak.api.v1alpha1.GetCapsuleRequest\x1a#.falak.api.v1alpha1.CapsuleResource\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1alpha1/capsules/{id}\x12u\n" +
	"\x04List\x12'.falak.api.v1alpha1.ListCapsulesRequest\x1a(.falak.api.v1alpha1.ListCapsulesResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1alpha1/capsules\x12{\n" +
	"\x06Update\x12(.falak.api.v1alpha1.UpdateCapsuleRequest\x1a#.falak.api.v1alpha1.CapsuleResource\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1alpha1/capsules/{id}\x12k\n" +
	"\x06Delete\x12(.falak.api.v1alpha1.DeleteCapsuleRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1alpha1/capsules/{id}\x12S\n" +
	"\x05Watch\x12(.falak.api.v1alpha1.WatchCapsulesRequest\x1a\x1e.falak.api.v1alpha1.WatchEvent0\x01\x12u\n" +
	"\x04Logs\x12\x1f.falak.api.v1alpha1.LogsRequest\x1a\x1c.falak.api.v1alpha1.LogEntry\",\x82\xd3\xe4\x93\x02&\x12$/v1alpha1/capsules/{capsule_id}/logs0\x01B2Z0github.com/tareksalem/falak/api/proto/v1alpha1pbb\x06proto3"

var (
	file_api_proto_v1alpha1_capsule_service_proto_rawDescOnce sync.Once
	file_api_proto_v1alpha1_capsule_service_proto_rawDescData []byte
)

func file_api_proto_v1alpha1_capsule_service_proto_rawDescGZIP() []byte {
	file_api_proto_v1alpha1_capsule_service_proto_rawDescOnce.Do(func() {
		file_api_proto_v1alpha1_capsule_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_capsule_service_proto_rawDesc), len(file_api_proto_v1alpha1_capsule_service_proto_rawDesc)))
	})
	return file_api_proto_v1alpha1_capsule_service_proto_rawDescData
}

var file_api_proto_v1alpha1_capsule_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_v1alpha1_capsule_service_proto_goTypes = []any{
	(*CapsuleResource)(nil),       // 0: falak.api.v1alpha1.CapsuleResource
	(*CapsuleSpec)(nil),           // 1: falak.api.v1alpha1.CapsuleSpec
	(*PortMapping)(nil),           // 2: falak.api.v1alpha1.PortMapping
	(*CapsuleStatus)(nil),         // 3: falak.api.v1alpha1.CapsuleStatus
	(*ReplicaStatus)(nil),         // 4: falak.api.v1alpha1.ReplicaStatus
	(*CreateCapsuleRequest)(nil),  // 5: falak.api.v1alpha1.CreateCapsuleRequest
	(*GetCapsuleRequest)(nil),     // 6: falak.api.v1alpha1.GetCapsuleRequest
	(*ListCapsulesRequest)(nil),   // 7: falak.api.v1alpha1.ListCapsulesRequest
	(*ListCapsulesResponse)(nil),  // 8: falak.api.v1alpha1.ListCapsulesResponse
	(*UpdateCapsuleRequest)(nil),  // 9: falak.api.v1alpha1.UpdateCapsuleRequest
	(*DeleteCapsuleRequest)(nil),  // 10: falak.api.v1alpha1.DeleteCapsuleRequest
	(*WatchCapsulesRequest)(nil),  // 11: falak.api.v1alpha1.WatchCapsulesRequest
	(*LogsRequest)(nil),           // 12: falak.api.v1alpha1.LogsRequest
	(*LogEntry)(nil),              // 13: falak.api.v1alpha1.LogEntry
	nil,                           // 14: falak.api.v1alpha1.CapsuleSpec.EnvEntry
	nil,                           // 15: falak.api.v1alpha1.CreateCapsuleRequest.LabelsEntry
	nil,                           // 16: falak.api.v1alpha1.CreateCapsuleRequest.EnvEntry
	nil,                           // 17: falak.api.v1alpha1.ListCapsulesRequest.LabelsEntry
	nil,                           // 18: falak.api.v1alpha1.UpdateCapsuleRequest.EnvEntry
	nil,                           // 19: falak.api.v1alpha1.WatchCapsulesRequest.LabelsEntry
	(*ObjectMeta)(nil),            // 20: falak.api.v1alpha1.ObjectMeta
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*Pagination)(nil),            // 22: falak.api.v1alpha1.Pagination
	(*PagedResult)(nil),           // 23: falak.api.v1alpha1.PagedResult
	(*emptypb.Empty)(nil),         // 24: google.protobuf.Empty
	(*WatchEvent)(nil),            // 25: falak.api.v1alpha1.WatchEvent
}
var file_api_proto_v1alpha1_capsule_service_proto_depIdxs = []int32{
	20, // 0: falak.api.v1alpha1.CapsuleResource.meta:type_name -> falak.api.v1alpha1.ObjectMeta
	1,  // 1: falak.api.v1alpha1.CapsuleResource.spec:type_name -> falak.api.v1alpha1.CapsuleSpec
	3,  // 2: falak.api.v1alpha1.CapsuleResource.status:type_name -> falak.api.v1alpha1.CapsuleStatus
	14, // 3: falak.api.v1alpha1.CapsuleSpec.env:type_name -> falak.api.v1alpha1.CapsuleSpec.EnvEntry
	2,  // 4: falak.api.v1alpha1.CapsuleSpec.ports:type_name -> falak.api.v1alpha1.PortMapping
	4,  // 5: falak.api.v1alpha1.CapsuleStatus.replicas:type_name -> falak.api.v1alpha1.ReplicaStatus
	21, // 6: falak.api.v1alpha1.ReplicaStatus.started_at:type_name -> google.protobuf.Timestamp
	2,  // 7: falak.api.v1alpha1.ReplicaStatus.ports:type_name -> falak.api.v1alpha1.PortMapping
	15, // 8: falak.api.v1alpha1.CreateCapsuleRequest.labels:type_name -> falak.api.v1alpha1.CreateCapsuleRequest.LabelsEntry
	16, // 9: falak.api.v1alpha1.CreateCapsuleRequest.env:type_name -> falak.api.v1alpha1.CreateCapsuleRequest.EnvEntry
	2,  // 10: falak.api.v1alpha1.CreateCapsuleRequest.ports:type_name -> falak.api.v1alpha1.PortMapping
	17, // 11: falak.api.v1alpha1.ListCapsulesRequest.labels:type_name -> falak.api.v1alpha1.ListCapsulesRequest.LabelsEntry
	22, // 12: falak.api.v1alpha1.ListCapsulesRequest.pagination:type_name -> falak.api.v1alpha1.Pagination
	0,  // 13: falak.api.v1alpha1.ListCapsulesResponse.capsules:type_name -> falak.api.v1alpha1.CapsuleResource
	23, // 14: falak.api.v1alpha1.ListCapsulesResponse.paging:type_name -> falak.api.v1alpha1.PagedResult
	18, // 15: falak.api.v1alpha1.UpdateCapsuleRequest.env:type_name -> falak.api.v1alpha1.UpdateCapsuleRequest.EnvEntry
	19, // 16: falak.api.v1alpha1.WatchCapsulesRequest.labels:type_name -> falak.api.v1alpha1.WatchCapsulesRequest.LabelsEntry
	21, // 17: falak.api.v1alpha1.LogsRequest.since:type_name -> google.protobuf.Timestamp
	21, // 18: falak.api.v1alpha1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 19: falak.api.v1alpha1.CapsuleService.Create:input_type -> falak.api.v1alpha1.CreateCapsuleRequest
	6,  // 20: falak.api.v1alpha1.CapsuleService.Get:input_type -> falak.api.v1alpha1.GetCapsuleRequest
	7,  // 21: falak.api.v1alpha1.CapsuleService.List:input_type -> falak.api.v1alpha1.ListCapsulesRequest
	9,  // 22: falak.api.v1alpha1.CapsuleService.Update:input_type -> falak.api.v1alpha1.UpdateCapsuleRequest
	10, // 23: falak.api.v1alpha1.CapsuleService.Delete:input_type -> falak.api.v1alpha1.DeleteCapsuleRequest
	11, // 24: falak.api.v1alpha1.CapsuleService.Watch:input_type -> falak.api.v1alpha1.WatchCapsulesRequest
	12, // 25: falak.api.v1alpha1.CapsuleService.Logs:input_type -> falak.api.v1alpha1.LogsRequest
	0,  // 26: falak.api.v1alpha1.CapsuleService.Create:output_type -> falak.api.v1alpha1.CapsuleResource
	0,  // 27: falak.api.v1alpha1.CapsuleService.Get:output_type -> falak.api.v1alpha1.CapsuleResource
	8,  // 28: falak.api.v1alpha1.CapsuleService.List:output_type -> falak.api.v1alpha1.ListCapsulesResponse
	0,  // 29: falak.api.v1alpha1.CapsuleService.Update:output_type -> falak.api.v1alpha1.CapsuleResource
	24, // 30: falak.api.v1alpha1.CapsuleService.Delete:output_type -> google.protobuf.Empty
	25, // 31: falak.api.v1alpha1.CapsuleService.Watch:output_type -> falak.api.v1alpha1.WatchEvent
	13, // 32: falak.api.v1alpha1.CapsuleService.Logs:output_type -> falak.api.v1alpha1.LogEntry
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_proto_v1alpha1_capsule_service_proto_init() }
func file_api_proto_v1alpha1_capsule_service_proto_init() {
	if File_api_proto_v1alpha1_capsule_service_proto != nil {
		return
	}
	file_api_proto_v1alpha1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_capsule_service_proto_rawDesc), len(file_api_proto_v1alpha1_capsule_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1alpha1_capsule_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1alpha1_capsule_service_proto_depIdxs,
		MessageInfos:      file_api_proto_v1alpha1_capsule_service_proto_msgTypes,
	}.Build()
	File_api_proto_v1alpha1_capsule_service_proto = out.File
	file_api_proto_v1alpha1_capsule_service_proto_goTypes = nil
	file_api_proto_v1alpha1_capsule_service_proto_depIdxs = nil
}
