// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1alpha1/common.proto

package v1alpha1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchEvent_Type int32

const (
	WatchEvent_ADDED    WatchEvent_Type = 0
	WatchEvent_MODIFIED WatchEvent_Type = 1
	WatchEvent_DELETED  WatchEvent_Type = 2
	WatchEvent_ERROR    WatchEvent_Type = 3
)

// Enum value maps for WatchEvent_Type.
var (
	WatchEvent_Type_name = map[int32]string{
		0: "ADDED",
		1: "MODIFIED",
		2: "DELETED",
		3: "ERROR",
	}
	WatchEvent_Type_value = map[string]int32{
		"ADDED":    0,
		"MODIFIED": 1,
		"DELETED":  2,
		"ERROR":    3,
	}
)

func (x WatchEvent_Type) Enum() *WatchEvent_Type {
	p := new(WatchEvent_Type)
	*p = x
	return p
}

func (x WatchEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1alpha1_common_proto_enumTypes[0].Descriptor()
}

func (WatchEvent_Type) Type() protoreflect.EnumType {
	return &file_api_proto_v1alpha1_common_proto_enumTypes[0]
}

func (x WatchEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEvent_Type.Descriptor instead.
func (WatchEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_common_proto_rawDescGZIP(), []int{3, 0}
}

// ObjectMeta carries common metadata for every API resource.
type ObjectMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Cluster       string                 `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectMeta) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ObjectMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObjectMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ObjectMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Pagination holds cursor-based pagination for List requests.
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// PagedResult carries pagination metadata in List responses.
type PagedResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagedResult) Reset() {
	*x = PagedResult{}
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagedResult) ProtoMessage() {}

func (x *PagedResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagedResult.ProtoReflect.Descriptor instead.
func (*PagedResult) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PagedResult) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PagedResult) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// WatchEvent is a single event in a Watch stream.
type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WatchEvent_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=falak.api.v1alpha1.WatchEvent_Type" json:"type,omitempty"`
	Resource      []byte                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"` // serialized resource
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_common_proto_rawDescGZIP(), []int{3}
}

func (x *WatchEvent) GetType() WatchEvent_Type {
	if x != nil {
		return x.Type
	}
	return WatchEvent_ADDED
}

func (x *WatchEvent) GetResource() []byte {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *WatchEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ErrorDetail carries structured error information.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // gRPC status code
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable message
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`     // field that caused the error (for validation)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_common_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorDetail) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

// HealthResponse is the response for health check endpoints.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok" or error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_common_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// SystemInfo is the response for system info endpoint.
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	GoVersion     string                 `protobuf:"bytes,4,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ApiAddress    string                 `protobuf:"bytes,7,opt,name=api_address,json=apiAddress,proto3" json:"api_address,omitempty"`
	Clusters      []string               `protobuf:"bytes,8,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_common_proto_rawDescGZIP(), []int{6}
}

func (x *SystemInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SystemInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *SystemInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *SystemInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SystemInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemInfo) GetApiAddress() string {
	if x != nil {
		return x.ApiAddress
	}
	return ""
}

func (x *SystemInfo) GetClusters() []string {
	if x != nil {
		return x.Clusters
	}
	return nil
}

var File_api_proto_v1alpha1_common_proto protoreflect.FileDescriptor

const file_api_proto_v1alpha1_common_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/v1alpha1/common.proto\x12\x12falak.api.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n" +
	"\n" +
	"ObjectMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\x12B\n" +
	"\x06labels\x18\x04 \x03(\v2*.falak.api.v1alpha1.ObjectMeta.LabelsEntryR\x06labels\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\n" +
	"Pagination\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"V\n" +
	"\vPagedResult\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xd4\x01\n" +
	"\n" +
	"WatchEvent\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.falak.api.v1alpha1.WatchEvent.TypeR\x04type\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\fR\bresource\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"7\n" +
	"\x04Type\x12\t\n" +
	"\x05ADDED\x10\x00\x12\f\n" +
	"\bMODIFIED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"Q\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xfb\x01\n" +
	"\n" +
	"SystemInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"go_version\x18\x04 \x01(\tR\tgoVersion\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vapi_address\x18\a \x01(\tR\n" +
	"apiAddress\x12\x1a\n" +
	"\bclusters\x18\b \x03(\tR\bclustersB2Z0github.com/tareksalem/falak/api/proto/v1alpha1pbb\x06proto3"

var (
	file_api_proto_v1alpha1_common_proto_rawDescOnce sync.Once
	file_api_proto_v1alpha1_common_proto_rawDescData []byte
)

func file_api_proto_v1alpha1_common_proto_rawDescGZIP() []byte {
	file_api_proto_v1alpha1_common_proto_rawDescOnce.Do(func() {
		file_api_proto_v1alpha1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_common_proto_rawDesc), len(file_api_proto_v1alpha1_common_proto_rawDesc)))
	})
	return file_api_proto_v1alpha1_common_proto_rawDescData
}

var file_api_proto_v1alpha1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1alpha1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_v1alpha1_common_proto_goTypes = []any{
	(WatchEvent_Type)(0),          // 0: falak.api.v1alpha1.WatchEvent.Type
	(*ObjectMeta)(nil),            // 1: falak.api.v1alpha1.ObjectMeta
	(*Pagination)(nil),            // 2: falak.api.v1alpha1.Pagination
	(*PagedResult)(nil),           // 3: falak.api.v1alpha1.PagedResult
	(*WatchEvent)(nil),            // 4: falak.api.v1alpha1.WatchEvent
	(*ErrorDetail)(nil),           // 5: falak.api.v1alpha1.ErrorDetail
	(*HealthResponse)(nil),        // 6: falak.api.v1alpha1.HealthResponse
	(*SystemInfo)(nil),            // 7: falak.api.v1alpha1.SystemInfo
	nil,                           // 8: falak.api.v1alpha1.ObjectMeta.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_proto_v1alpha1_common_proto_depIdxs = []int32{
	8, // 0: falak.api.v1alpha1.ObjectMeta.labels:type_name -> falak.api.v1alpha1.ObjectMeta.LabelsEntry
	9, // 1: falak.api.v1alpha1.ObjectMeta.created_at:type_name -> google.protobuf.Timestamp
	9, // 2: falak.api.v1alpha1.ObjectMeta.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: falak.api.v1alpha1.WatchEvent.type:type_name -> falak.api.v1alpha1.WatchEvent.Type
	9, // 4: falak.api.v1alpha1.WatchEvent.timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_v1alpha1_common_proto_init() }
func file_api_proto_v1alpha1_common_proto_init() {
	if File_api_proto_v1alpha1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_common_proto_rawDesc), len(file_api_proto_v1alpha1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1alpha1_common_proto_goTypes,
		DependencyIndexes: file_api_proto_v1alpha1_common_proto_depIdxs,
		EnumInfos:         file_api_proto_v1alpha1_common_proto_enumTypes,
		MessageInfos:      file_api_proto_v1alpha1_common_proto_msgTypes,
	}.Build()
	File_api_proto_v1alpha1_common_proto = out.File
	file_api_proto_v1alpha1_common_proto_goTypes = nil
	file_api_proto_v1alpha1_common_proto_depIdxs = nil
}
