// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: node_service.proto

package v1alpha1pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_node_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListNodesRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_node_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // peer ID or operator-assigned name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_node_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_node_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetNodeRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *GetNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_node_service_proto protoreflect.FileDescriptor

const file_node_service_proto_rawDesc = "" +
	"\n" +
	"\x12node_service.proto\x12\x12falak.api.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x15cluster_service.proto\",\n" +
	"\x10ListNodesRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\"G\n" +
	"\x11ListNodesResponse\x122\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.falak.api.v1alpha1.NodeInfoR\x05nodes\":\n" +
	"\x0eGetNodeRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id2\x8d\x03\n" +
	"\vNodeService\x12\x7f\n" +
	"\x04List\x12$.falak.api.v1alpha1.ListNodesRequest\x1a%.falak.api.v1alpha1.ListNodesResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1alpha1/clusters/{cluster}/nodes\x12x\n" +
	"\x03Get\x12\".falak.api.v1alpha1.GetNodeRequest\x1a\x1c.falak.api.v1alpha1.NodeInfo\"/\x82\xd3\xe4\x93\x02)\x12'/v1alpha1/clusters/{cluster}/nodes/{id}\x12\x82\x01\n" +
	"\x06Health\x12\".falak.api.v1alpha1.GetNodeRequest\x1a\x1c.falak.api.v1alpha1.NodeInfo\"6\x82\xd3\xe4\x93\x020\x12./v1alpha1/clusters/{cluster}/nodes/{id}/healthB2Z0github.com/tareksalem/falak/api/proto/v1alpha1pbb\x06proto3"

var (
	file_node_service_proto_rawDescOnce sync.Once
	file_node_service_proto_rawDescData []byte
)

func file_node_service_proto_rawDescGZIP() []byte {
	file_node_service_proto_rawDescOnce.Do(func() {
		file_node_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_service_proto_rawDesc), len(file_node_service_proto_rawDesc)))
	})
	return file_node_service_proto_rawDescData
}

var file_node_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_node_service_proto_goTypes = []any{
	(*ListNodesRequest)(nil),  // 0: falak.api.v1alpha1.ListNodesRequest
	(*ListNodesResponse)(nil), // 1: falak.api.v1alpha1.ListNodesResponse
	(*GetNodeRequest)(nil),    // 2: falak.api.v1alpha1.GetNodeRequest
	(*NodeInfo)(nil),          // 3: falak.api.v1alpha1.NodeInfo
}
var file_node_service_proto_depIdxs = []int32{
	3, // 0: falak.api.v1alpha1.ListNodesResponse.nodes:type_name -> falak.api.v1alpha1.NodeInfo
	0, // 1: falak.api.v1alpha1.NodeService.List:input_type -> falak.api.v1alpha1.ListNodesRequest
	2, // 2: falak.api.v1alpha1.NodeService.Get:input_type -> falak.api.v1alpha1.GetNodeRequest
	2, // 3: falak.api.v1alpha1.NodeService.Health:input_type -> falak.api.v1alpha1.GetNodeRequest
	1, // 4: falak.api.v1alpha1.NodeService.List:output_type -> falak.api.v1alpha1.ListNodesResponse
	3, // 5: falak.api.v1alpha1.NodeService.Get:output_type -> falak.api.v1alpha1.NodeInfo
	3, // 6: falak.api.v1alpha1.NodeService.Health:output_type -> falak.api.v1alpha1.NodeInfo
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_service_proto_init() }
func file_node_service_proto_init() {
	if File_node_service_proto != nil {
		return
	}
	file_cluster_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_service_proto_rawDesc), len(file_node_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_service_proto_goTypes,
		DependencyIndexes: file_node_service_proto_depIdxs,
		MessageInfos:      file_node_service_proto_msgTypes,
	}.Build()
	File_node_service_proto = out.File
	file_node_service_proto_goTypes = nil
	file_node_service_proto_depIdxs = nil
}
