// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1alpha1/service_service.proto

package v1alpha1pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ObjectMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Spec          *ServiceSpec           `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *ServiceStatus         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceResource) Reset() {
	*x = ServiceResource{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResource) ProtoMessage() {}

func (x *ServiceResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResource.ProtoReflect.Descriptor instead.
func (*ServiceResource) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceResource) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ServiceResource) GetSpec() *ServiceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ServiceResource) GetStatus() *ServiceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ServiceSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// visibility is "group" or "cluster" (default cluster). external is reserved.
	Visibility    string            `protobuf:"bytes,1,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Group         string            `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Ports         []*ServicePort    `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Backends      []*ServiceBackend `protobuf:"bytes,4,rep,name=backends,proto3" json:"backends,omitempty"`
	Strategy      *Strategy         `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Timeouts      *ServiceTimeouts  `protobuf:"bytes,6,opt,name=timeouts,proto3" json:"timeouts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSpec) Reset() {
	*x = ServiceSpec{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSpec) ProtoMessage() {}

func (x *ServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSpec.ProtoReflect.Descriptor instead.
func (*ServiceSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceSpec) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ServiceSpec) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ServiceSpec) GetPorts() []*ServicePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ServiceSpec) GetBackends() []*ServiceBackend {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *ServiceSpec) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *ServiceSpec) GetTimeouts() *ServiceTimeouts {
	if x != nil {
		return x.Timeouts
	}
	return nil
}

type ServicePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // "tcp" or "udp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePort) Reset() {
	*x = ServicePort{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePort) ProtoMessage() {}

func (x *ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePort.ProtoReflect.Descriptor instead.
func (*ServicePort) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicePort) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServicePort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ServiceBackend struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Capsule           string                 `protobuf:"bytes,1,opt,name=capsule,proto3" json:"capsule,omitempty"`
	CapturedCapsuleId string                 `protobuf:"bytes,2,opt,name=captured_capsule_id,json=capturedCapsuleId,proto3" json:"captured_capsule_id,omitempty"`
	PortMap           map[string]string      `protobuf:"bytes,3,rep,name=port_map,json=portMap,proto3" json:"port_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Weight            int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServiceBackend) Reset() {
	*x = ServiceBackend{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceBackend) ProtoMessage() {}

func (x *ServiceBackend) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceBackend.ProtoReflect.Descriptor instead.
func (*ServiceBackend) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceBackend) GetCapsule() string {
	if x != nil {
		return x.Capsule
	}
	return ""
}

func (x *ServiceBackend) GetCapturedCapsuleId() string {
	if x != nil {
		return x.CapturedCapsuleId
	}
	return ""
}

func (x *ServiceBackend) GetPortMap() map[string]string {
	if x != nil {
		return x.PortMap
	}
	return nil
}

func (x *ServiceBackend) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Strategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "static" | "canary" | "blue-green"
	Canary        *CanaryStrategy        `protobuf:"bytes,2,opt,name=canary,proto3" json:"canary,omitempty"`
	BlueGreen     *BlueGreenStrategy     `protobuf:"bytes,3,opt,name=blue_green,json=blueGreen,proto3" json:"blue_green,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Strategy) Reset() {
	*x = Strategy{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strategy) ProtoMessage() {}

func (x *Strategy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strategy.ProtoReflect.Descriptor instead.
func (*Strategy) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{4}
}

func (x *Strategy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Strategy) GetCanary() *CanaryStrategy {
	if x != nil {
		return x.Canary
	}
	return nil
}

func (x *Strategy) GetBlueGreen() *BlueGreenStrategy {
	if x != nil {
		return x.BlueGreen
	}
	return nil
}

type CanaryStrategy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Target          string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	From            string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Step            int32                  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	IntervalMs      int64                  `protobuf:"varint,4,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	SuccessCriteria []string               `protobuf:"bytes,5,rep,name=success_criteria,json=successCriteria,proto3" json:"success_criteria,omitempty"`
	AbortOn         []string               `protobuf:"bytes,6,rep,name=abort_on,json=abortOn,proto3" json:"abort_on,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CanaryStrategy) Reset() {
	*x = CanaryStrategy{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanaryStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanaryStrategy) ProtoMessage() {}

func (x *CanaryStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanaryStrategy.ProtoReflect.Descriptor instead.
func (*CanaryStrategy) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{5}
}

func (x *CanaryStrategy) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CanaryStrategy) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CanaryStrategy) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *CanaryStrategy) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *CanaryStrategy) GetSuccessCriteria() []string {
	if x != nil {
		return x.SuccessCriteria
	}
	return nil
}

func (x *CanaryStrategy) GetAbortOn() []string {
	if x != nil {
		return x.AbortOn
	}
	return nil
}

type BlueGreenStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        string                 `protobuf:"bytes,1,opt,name=active,proto3" json:"active,omitempty"`
	DrainMs       int64                  `protobuf:"varint,2,opt,name=drain_ms,json=drainMs,proto3" json:"drain_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlueGreenStrategy) Reset() {
	*x = BlueGreenStrategy{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlueGreenStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlueGreenStrategy) ProtoMessage() {}

func (x *BlueGreenStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlueGreenStrategy.ProtoReflect.Descriptor instead.
func (*BlueGreenStrategy) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{6}
}

func (x *BlueGreenStrategy) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

func (x *BlueGreenStrategy) GetDrainMs() int64 {
	if x != nil {
		return x.DrainMs
	}
	return 0
}

type ServiceTimeouts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdleMs        int64                  `protobuf:"varint,1,opt,name=idle_ms,json=idleMs,proto3" json:"idle_ms,omitempty"`
	ConnectMs     int64                  `protobuf:"varint,2,opt,name=connect_ms,json=connectMs,proto3" json:"connect_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTimeouts) Reset() {
	*x = ServiceTimeouts{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTimeouts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTimeouts) ProtoMessage() {}

func (x *ServiceTimeouts) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTimeouts.ProtoReflect.Descriptor instead.
func (*ServiceTimeouts) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceTimeouts) GetIdleMs() int64 {
	if x != nil {
		return x.IdleMs
	}
	return 0
}

func (x *ServiceTimeouts) GetConnectMs() int64 {
	if x != nil {
		return x.ConnectMs
	}
	return 0
}

type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // created|active|draining|deleted|canary_aborted|placement_failed
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BackendStates []*BackendState        `protobuf:"bytes,3,rep,name=backend_states,json=backendStates,proto3" json:"backend_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceStatus) GetBackendStates() []*BackendState {
	if x != nil {
		return x.BackendStates
	}
	return nil
}

type BackendState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Backend           string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Resolution        string                 `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"` // resolved|unresolved|unresolved_capsule_deleted|unresolved_identity_changed
	CapturedCapsuleId string                 `protobuf:"bytes,3,opt,name=captured_capsule_id,json=capturedCapsuleId,proto3" json:"captured_capsule_id,omitempty"`
	LastResolvedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_resolved_at,json=lastResolvedAt,proto3" json:"last_resolved_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BackendState) Reset() {
	*x = BackendState{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendState) ProtoMessage() {}

func (x *BackendState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendState.ProtoReflect.Descriptor instead.
func (*BackendState) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{9}
}

func (x *BackendState) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *BackendState) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *BackendState) GetCapturedCapsuleId() string {
	if x != nil {
		return x.CapturedCapsuleId
	}
	return ""
}

func (x *BackendState) GetLastResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastResolvedAt
	}
	return nil
}

type CreateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Spec          *ServiceSpec           `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // logical Service name; promoted out of spec to match CLI ergonomics.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateServiceRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *CreateServiceRequest) GetSpec() *ServiceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetServiceRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Visibility    string                 `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListServicesRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ListServicesRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ListServicesRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ListServicesRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceResource     `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Paging        *PagedResult           `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListServicesResponse) GetServices() []*ServiceResource {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListServicesResponse) GetPaging() *PagedResult {
	if x != nil {
		return x.Paging
	}
	return nil
}

type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Spec          *ServiceSpec           `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *UpdateServiceRequest) GetSpec() *ServiceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteServiceRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

type ApplyServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *ServiceSpec           `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyServiceRequest) Reset() {
	*x = ApplyServiceRequest{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyServiceRequest) ProtoMessage() {}

func (x *ApplyServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyServiceRequest.ProtoReflect.Descriptor instead.
func (*ApplyServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{16}
}

func (x *ApplyServiceRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ApplyServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplyServiceRequest) GetSpec() *ServiceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type RebindServiceBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Cluster       string                 `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebindServiceBackendRequest) Reset() {
	*x = RebindServiceBackendRequest{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebindServiceBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebindServiceBackendRequest) ProtoMessage() {}

func (x *RebindServiceBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebindServiceBackendRequest.ProtoReflect.Descriptor instead.
func (*RebindServiceBackendRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{17}
}

func (x *RebindServiceBackendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RebindServiceBackendRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *RebindServiceBackendRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

type WatchServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchServicesRequest) Reset() {
	*x = WatchServicesRequest{}
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchServicesRequest) ProtoMessage() {}

func (x *WatchServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_service_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchServicesRequest.ProtoReflect.Descriptor instead.
func (*WatchServicesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_service_service_proto_rawDescGZIP(), []int{18}
}

func (x *WatchServicesRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

var File_api_proto_v1alpha1_service_service_proto protoreflect.FileDescriptor

const file_api_proto_v1alpha1_service_service_proto_rawDesc = "" +
	"\n" +
	"(api/proto/v1alpha1/service_service.proto\x12\x12falak.api.v1alpha1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fapi/proto/v1alpha1/common.proto\"\xb5\x01\n" +
	"\x0fServiceResource\x122\n" +
	"\x04meta\x18\x01 \x01(\v2\x1e.falak.api.v1alpha1.ObjectMetaR\x04meta\x123\n" +
	"\x04spec\x18\x02 \x01(\v2\x1f.falak.api.v1alpha1.ServiceSpecR\x04spec\x129\n" +
	"\x06status\x18\x03 \x01(\v2!.falak.api.v1alpha1.ServiceStatusR\x06status\"\xb5\x02\n" +
	"\vServiceSpec\x12\x1e\n" +
	"\n" +
	"visibility\x18\x01 \x01(\tR\n" +
	"visibility\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x125\n" +
	"\x05ports\x18\x03 \x03(\v2\x1f.falak.api.v1alpha1.ServicePortR\x05ports\x12>\n" +
	"\bbackends\x18\x04 \x03(\v2\".falak.api.v1alpha1.ServiceBackendR\bbackends\x128\n" +
	"\bstrategy\x18\x05 \x01(\v2\x1c.falak.api.v1alpha1.StrategyR\bstrategy\x12?\n" +
	"\btimeouts\x18\x06 \x01(\v2#.falak.api.v1alpha1.ServiceTimeoutsR\btimeouts\"Q\n" +
	"\vServicePort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xfa\x01\n" +
	"\x0eServiceBackend\x12\x18\n" +
	"\acapsule\x18\x01 \x01(\tR\acapsule\x12.\n" +
	"\x13captured_capsule_id\x18\x02 \x01(\tR\x11capturedCapsuleId\x12J\n" +
	"\bport_map\x18\x03 \x03(\v2/.falak.api.v1alpha1.ServiceBackend.PortMapEntryR\aportMap\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x1a:\n" +
	"\fPortMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\bStrategy\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12:\n" +
	"\x06canary\x18\x02 \x01(\v2\".falak.api.v1alpha1.CanaryStrategyR\x06canary\x12D\n" +
	"\n" +
	"blue_green\x18\x03 \x01(\v2%.falak.api.v1alpha1.BlueGreenStrategyR\tblueGreen\"\xb7\x01\n" +
	"\x0eCanaryStrategy\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x05R\x04step\x12\x1f\n" +
	"\vinterval_ms\x18\x04 \x01(\x03R\n" +
	"intervalMs\x12)\n" +
	"\x10success_criteria\x18\x05 \x03(\tR\x0fsuccessCriteria\x12\x19\n" +
	"\babort_on\x18\x06 \x03(\tR\aabortOn\"F\n" +
	"\x11BlueGreenStrategy\x12\x16\n" +
	"\x06active\x18\x01 \x01(\tR\x06active\x12\x19\n" +
	"\bdrain_ms\x18\x02 \x01(\x03R\adrainMs\"I\n" +
	"\x0fServiceTimeouts\x12\x17\n" +
	"\aidle_ms\x18\x01 \x01(\x03R\x06idleMs\x12\x1d\n" +
	"\n" +
	"connect_ms\x18\x02 \x01(\x03R\tconnectMs\"\x8a\x01\n" +
	"\rServiceStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12G\n" +
	"\x0ebackend_states\x18\x03 \x03(\v2 .falak.api.v1alpha1.BackendStateR\rbackendStates\"\xbe\x01\n" +
	"\fBackendState\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12.\n" +
	"\x13captured_capsule_id\x18\x03 \x01(\tR\x11capturedCapsuleId\x12D\n" +
	"\x10last_resolved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastResolvedAt\"y\n" +
	"\x14CreateServiceRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x123\n" +
	"\x04spec\x18\x02 \x01(\v2\x1f.falak.api.v1alpha1.ServiceSpecR\x04spec\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"A\n" +
	"\x11GetServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\"\xa5\x01\n" +
	"\x13ListServicesRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1e\n" +
	"\n" +
	"visibility\x18\x02 \x01(\tR\n" +
	"visibility\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12>\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1e.falak.api.v1alpha1.PaginationR\n" +
	"pagination\"\x90\x01\n" +
	"\x14ListServicesResponse\x12?\n" +
	"\bservices\x18\x01 \x03(\v2#.falak.api.v1alpha1.ServiceResourceR\bservices\x127\n" +
	"\x06paging\x18\x02 \x01(\v2\x1f.falak.api.v1alpha1.PagedResultR\x06paging\"y\n" +
	"\x14UpdateServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x123\n" +
	"\x04spec\x18\x03 \x01(\v2\x1f.falak.api.v1alpha1.ServiceSpecR\x04spec\"D\n" +
	"\x14DeleteServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\"x\n" +
	"\x13ApplyServiceRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\x04spec\x18\x03 \x01(\v2\x1f.falak.api.v1alpha1.ServiceSpecR\x04spec\"e\n" +
	"\x1bRebindServiceBackendRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\"0\n" +
	"\x14WatchServicesRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster2\xd3\a\n" +
	"\x0eServiceService\x12v\n" +
	"\x06Create\x12(.falak.api.v1alpha1.CreateServiceRequest\x1a#.falak.api.v1alpha1.ServiceResource\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1alpha1/services\x12t\n" +
	"\x03Get\x12%.falak.api.v1alpha1.GetServiceRequest\x1a#.falak.api.v1alpha1.ServiceResource\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1alpha1/services/{name}\x12u\n" +
	"\x04List\x12'.falak.api.v1alpha1.ListServicesRequest\x1a(.falak.api.v1alpha1.ListServicesResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1alpha1/services\x12}\n" +
	"\x06Update\x12(.falak.api.v1alpha1.UpdateServiceRequest\x1a#.falak.api.v1alpha1.ServiceResource\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/v1alpha1/services/{name}\x12m\n" +
	"\x06Delete\x12(.falak.api.v1alpha1.DeleteServiceRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1alpha1/services/{name}\x12z\n" +
	"\x05Apply\x12'.falak.api.v1alpha1.ApplyServiceRequest\x1a#.falak.api.v1alpha1.ServiceResource\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1alpha1/services:apply\x12\x9c\x01\n" +
	"\rRebindBackend\x12/.falak.api.v1alpha1.RebindServiceBackendRequest\x1a#.falak.api.v1alpha1.ServiceResource\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1alpha1/services/{name}/rebind/{backend}\x12S\n" +
	"\x05Watch\x12(.falak.api.v1alpha1.WatchServicesRequest\x1a\x1e.falak.api.v1alpha1.WatchEvent0\x01B2Z0github.com/tareksalem/falak/api/proto/v1alpha1pbb\x06proto3"

var (
	file_api_proto_v1alpha1_service_service_proto_rawDescOnce sync.Once
	file_api_proto_v1alpha1_service_service_proto_rawDescData []byte
)

func file_api_proto_v1alpha1_service_service_proto_rawDescGZIP() []byte {
	file_api_proto_v1alpha1_service_service_proto_rawDescOnce.Do(func() {
		file_api_proto_v1alpha1_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_service_service_proto_rawDesc), len(file_api_proto_v1alpha1_service_service_proto_rawDesc)))
	})
	return file_api_proto_v1alpha1_service_service_proto_rawDescData
}

var file_api_proto_v1alpha1_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_v1alpha1_service_service_proto_goTypes = []any{
	(*ServiceResource)(nil),             // 0: falak.api.v1alpha1.ServiceResource
	(*ServiceSpec)(nil),                 // 1: falak.api.v1alpha1.ServiceSpec
	(*ServicePort)(nil),                 // 2: falak.api.v1alpha1.ServicePort
	(*ServiceBackend)(nil),              // 3: falak.api.v1alpha1.ServiceBackend
	(*Strategy)(nil),                    // 4: falak.api.v1alpha1.Strategy
	(*CanaryStrategy)(nil),              // 5: falak.api.v1alpha1.CanaryStrategy
	(*BlueGreenStrategy)(nil),           // 6: falak.api.v1alpha1.BlueGreenStrategy
	(*ServiceTimeouts)(nil),             // 7: falak.api.v1alpha1.ServiceTimeouts
	(*ServiceStatus)(nil),               // 8: falak.api.v1alpha1.ServiceStatus
	(*BackendState)(nil),                // 9: falak.api.v1alpha1.BackendState
	(*CreateServiceRequest)(nil),        // 10: falak.api.v1alpha1.CreateServiceRequest
	(*GetServiceRequest)(nil),           // 11: falak.api.v1alpha1.GetServiceRequest
	(*ListServicesRequest)(nil),         // 12: falak.api.v1alpha1.ListServicesRequest
	(*ListServicesResponse)(nil),        // 13: falak.api.v1alpha1.ListServicesResponse
	(*UpdateServiceRequest)(nil),        // 14: falak.api.v1alpha1.UpdateServiceRequest
	(*DeleteServiceRequest)(nil),        // 15: falak.api.v1alpha1.DeleteServiceRequest
	(*ApplyServiceRequest)(nil),         // 16: falak.api.v1alpha1.ApplyServiceRequest
	(*RebindServiceBackendRequest)(nil), // 17: falak.api.v1alpha1.RebindServiceBackendRequest
	(*WatchServicesRequest)(nil),        // 18: falak.api.v1alpha1.WatchServicesRequest
	nil,                                 // 19: falak.api.v1alpha1.ServiceBackend.PortMapEntry
	(*ObjectMeta)(nil),                  // 20: falak.api.v1alpha1.ObjectMeta
	(*timestamppb.Timestamp)(nil),       // 21: google.protobuf.Timestamp
	(*Pagination)(nil),                  // 22: falak.api.v1alpha1.Pagination
	(*PagedResult)(nil),                 // 23: falak.api.v1alpha1.PagedResult
	(*emptypb.Empty)(nil),               // 24: google.protobuf.Empty
	(*WatchEvent)(nil),                  // 25: falak.api.v1alpha1.WatchEvent
}
var file_api_proto_v1alpha1_service_service_proto_depIdxs = []int32{
	20, // 0: falak.api.v1alpha1.ServiceResource.meta:type_name -> falak.api.v1alpha1.ObjectMeta
	1,  // 1: falak.api.v1alpha1.ServiceResource.spec:type_name -> falak.api.v1alpha1.ServiceSpec
	8,  // 2: falak.api.v1alpha1.ServiceResource.status:type_name -> falak.api.v1alpha1.ServiceStatus
	2,  // 3: falak.api.v1alpha1.ServiceSpec.ports:type_name -> falak.api.v1alpha1.ServicePort
	3,  // 4: falak.api.v1alpha1.ServiceSpec.backends:type_name -> falak.api.v1alpha1.ServiceBackend
	4,  // 5: falak.api.v1alpha1.ServiceSpec.strategy:type_name -> falak.api.v1alpha1.Strategy
	7,  // 6: falak.api.v1alpha1.ServiceSpec.timeouts:type_name -> falak.api.v1alpha1.ServiceTimeouts
	19, // 7: falak.api.v1alpha1.ServiceBackend.port_map:type_name -> falak.api.v1alpha1.ServiceBackend.PortMapEntry
	5,  // 8: falak.api.v1alpha1.Strategy.canary:type_name -> falak.api.v1alpha1.CanaryStrategy
	6,  // 9: falak.api.v1alpha1.Strategy.blue_green:type_name -> falak.api.v1alpha1.BlueGreenStrategy
	9,  // 10: falak.api.v1alpha1.ServiceStatus.backend_states:type_name -> falak.api.v1alpha1.BackendState
	21, // 11: falak.api.v1alpha1.BackendState.last_resolved_at:type_name -> google.protobuf.Timestamp
	1,  // 12: falak.api.v1alpha1.CreateServiceRequest.spec:type_name -> falak.api.v1alpha1.ServiceSpec
	22, // 13: falak.api.v1alpha1.ListServicesRequest.pagination:type_name -> falak.api.v1alpha1.Pagination
	0,  // 14: falak.api.v1alpha1.ListServicesResponse.services:type_name -> falak.api.v1alpha1.ServiceResource
	23, // 15: falak.api.v1alpha1.ListServicesResponse.paging:type_name -> falak.api.v1alpha1.PagedResult
	1,  // 16: falak.api.v1alpha1.UpdateServiceRequest.spec:type_name -> falak.api.v1alpha1.ServiceSpec
	1,  // 17: falak.api.v1alpha1.ApplyServiceRequest.spec:type_name -> falak.api.v1alpha1.ServiceSpec
	10, // 18: falak.api.v1alpha1.ServiceService.Create:input_type -> falak.api.v1alpha1.CreateServiceRequest
	11, // 19: falak.api.v1alpha1.ServiceService.Get:input_type -> falak.api.v1alpha1.GetServiceRequest
	12, // 20: falak.api.v1alpha1.ServiceService.List:input_type -> falak.api.v1alpha1.ListServicesRequest
	14, // 21: falak.api.v1alpha1.ServiceService.Update:input_type -> falak.api.v1alpha1.UpdateServiceRequest
	15, // 22: falak.api.v1alpha1.ServiceService.Delete:input_type -> falak.api.v1alpha1.DeleteServiceRequest
	16, // 23: falak.api.v1alpha1.ServiceService.Apply:input_type -> falak.api.v1alpha1.ApplyServiceRequest
	17, // 24: falak.api.v1alpha1.ServiceService.RebindBackend:input_type -> falak.api.v1alpha1.RebindServiceBackendRequest
	18, // 25: falak.api.v1alpha1.ServiceService.Watch:input_type -> falak.api.v1alpha1.WatchServicesRequest
	0,  // 26: falak.api.v1alpha1.ServiceService.Create:output_type -> falak.api.v1alpha1.ServiceResource
	0,  // 27: falak.api.v1alpha1.ServiceService.Get:output_type -> falak.api.v1alpha1.ServiceResource
	13, // 28: falak.api.v1alpha1.ServiceService.List:output_type -> falak.api.v1alpha1.ListServicesResponse
	0,  // 29: falak.api.v1alpha1.ServiceService.Update:output_type -> falak.api.v1alpha1.ServiceResource
	24, // 30: falak.api.v1alpha1.ServiceService.Delete:output_type -> google.protobuf.Empty
	0,  // 31: falak.api.v1alpha1.ServiceService.Apply:output_type -> falak.api.v1alpha1.ServiceResource
	0,  // 32: falak.api.v1alpha1.ServiceService.RebindBackend:output_type -> falak.api.v1alpha1.ServiceResource
	25, // 33: falak.api.v1alpha1.ServiceService.Watch:output_type -> falak.api.v1alpha1.WatchEvent
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_v1alpha1_service_service_proto_init() }
func file_api_proto_v1alpha1_service_service_proto_init() {
	if File_api_proto_v1alpha1_service_service_proto != nil {
		return
	}
	file_api_proto_v1alpha1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_service_service_proto_rawDesc), len(file_api_proto_v1alpha1_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1alpha1_service_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1alpha1_service_service_proto_depIdxs,
		MessageInfos:      file_api_proto_v1alpha1_service_service_proto_msgTypes,
	}.Build()
	File_api_proto_v1alpha1_service_service_proto = out.File
	file_api_proto_v1alpha1_service_service_proto_goTypes = nil
	file_api_proto_v1alpha1_service_service_proto_depIdxs = nil
}
