// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/v1alpha1/service_service.proto

package v1alpha1pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceService_Create_FullMethodName        = "/falak.api.v1alpha1.ServiceService/Create"
	ServiceService_Get_FullMethodName           = "/falak.api.v1alpha1.ServiceService/Get"
	ServiceService_List_FullMethodName          = "/falak.api.v1alpha1.ServiceService/List"
	ServiceService_Update_FullMethodName        = "/falak.api.v1alpha1.ServiceService/Update"
	ServiceService_Delete_FullMethodName        = "/falak.api.v1alpha1.ServiceService/Delete"
	ServiceService_Apply_FullMethodName         = "/falak.api.v1alpha1.ServiceService/Apply"
	ServiceService_RebindBackend_FullMethodName = "/falak.api.v1alpha1.ServiceService/RebindBackend"
	ServiceService_Watch_FullMethodName         = "/falak.api.v1alpha1.ServiceService/Watch"
)

// ServiceServiceClient is the client API for ServiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ServiceService manages Falak Service entities — logical names with
// weighted backends and traffic-management strategies. Decoupled from
// any single capsule; deleting a Service stops routing only.
type ServiceServiceClient interface {
	// Create admits a new Service. Backends are resolved leniently —
	// unknown backend capsules are accepted and bound when they appear.
	Create(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*ServiceResource, error)
	// Get returns a Service by name.
	Get(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*ServiceResource, error)
	// List returns every Service known to this node.
	List(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// Update replaces the spec on an existing Service. Captured backend
	// IDs are preserved when a backend stays in the new spec.
	Update(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*ServiceResource, error)
	// Delete removes a Service. Capsules referenced by the Service are
	// never touched — only routing stops.
	Delete(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Apply is the declarative upsert: create when absent, update otherwise.
	Apply(ctx context.Context, in *ApplyServiceRequest, opts ...grpc.CallOption) (*ServiceResource, error)
	// RebindBackend clears the captured capsule ID on a backend so the
	// current capsule with that name binds on the next resolve pass.
	// Used after a delete+recreate of a backend capsule.
	RebindBackend(ctx context.Context, in *RebindServiceBackendRequest, opts ...grpc.CallOption) (*ServiceResource, error)
	// Watch streams Service lifecycle events.
	Watch(ctx context.Context, in *WatchServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
}

type serviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceServiceClient(cc grpc.ClientConnInterface) ServiceServiceClient {
	return &serviceServiceClient{cc}
}

func (c *serviceServiceClient) Create(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*ServiceResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResource)
	err := c.cc.Invoke(ctx, ServiceService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) Get(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*ServiceResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResource)
	err := c.cc.Invoke(ctx, ServiceService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) List(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ServiceService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) Update(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*ServiceResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResource)
	err := c.cc.Invoke(ctx, ServiceService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) Delete(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ServiceService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) Apply(ctx context.Context, in *ApplyServiceRequest, opts ...grpc.CallOption) (*ServiceResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResource)
	err := c.cc.Invoke(ctx, ServiceService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) RebindBackend(ctx context.Context, in *RebindServiceBackendRequest, opts ...grpc.CallOption) (*ServiceResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResource)
	err := c.cc.Invoke(ctx, ServiceService_RebindBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) Watch(ctx context.Context, in *WatchServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServiceService_ServiceDesc.Streams[0], ServiceService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchServicesRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceService_WatchClient = grpc.ServerStreamingClient[WatchEvent]

// ServiceServiceServer is the server API for ServiceService service.
// All implementations must embed UnimplementedServiceServiceServer
// for forward compatibility.
//
// ServiceService manages Falak Service entities — logical names with
// weighted backends and traffic-management strategies. Decoupled from
// any single capsule; deleting a Service stops routing only.
type ServiceServiceServer interface {
	// Create admits a new Service. Backends are resolved leniently —
	// unknown backend capsules are accepted and bound when they appear.
	Create(context.Context, *CreateServiceRequest) (*ServiceResource, error)
	// Get returns a Service by name.
	Get(context.Context, *GetServiceRequest) (*ServiceResource, error)
	// List returns every Service known to this node.
	List(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// Update replaces the spec on an existing Service. Captured backend
	// IDs are preserved when a backend stays in the new spec.
	Update(context.Context, *UpdateServiceRequest) (*ServiceResource, error)
	// Delete removes a Service. Capsules referenced by the Service are
	// never touched — only routing stops.
	Delete(context.Context, *DeleteServiceRequest) (*emptypb.Empty, error)
	// Apply is the declarative upsert: create when absent, update otherwise.
	Apply(context.Context, *ApplyServiceRequest) (*ServiceResource, error)
	// RebindBackend clears the captured capsule ID on a backend so the
	// current capsule with that name binds on the next resolve pass.
	// Used after a delete+recreate of a backend capsule.
	RebindBackend(context.Context, *RebindServiceBackendRequest) (*ServiceResource, error)
	// Watch streams Service lifecycle events.
	Watch(*WatchServicesRequest, grpc.ServerStreamingServer[WatchEvent]) error
	mustEmbedUnimplementedServiceServiceServer()
}

// UnimplementedServiceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServiceServer struct{}

func (UnimplementedServiceServiceServer) Create(context.Context, *CreateServiceRequest) (*ServiceResource, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedServiceServiceServer) Get(context.Context, *GetServiceRequest) (*ServiceResource, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedServiceServiceServer) List(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedServiceServiceServer) Update(context.Context, *UpdateServiceRequest) (*ServiceResource, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedServiceServiceServer) Delete(context.Context, *DeleteServiceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedServiceServiceServer) Apply(context.Context, *ApplyServiceRequest) (*ServiceResource, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedServiceServiceServer) RebindBackend(context.Context, *RebindServiceBackendRequest) (*ServiceResource, error) {
	return nil, status.Error(codes.Unimplemented, "method RebindBackend not implemented")
}
func (UnimplementedServiceServiceServer) Watch(*WatchServicesRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedServiceServiceServer) mustEmbedUnimplementedServiceServiceServer() {}
func (UnimplementedServiceServiceServer) testEmbeddedByValue()                        {}

// UnsafeServiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServiceServer will
// result in compilation errors.
type UnsafeServiceServiceServer interface {
	mustEmbedUnimplementedServiceServiceServer()
}

func RegisterServiceServiceServer(s grpc.ServiceRegistrar, srv ServiceServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceService_ServiceDesc, srv)
}

func _ServiceService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).Create(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).Get(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).List(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).Update(ctx, req.(*UpdateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).Delete(ctx, req.(*DeleteServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).Apply(ctx, req.(*ApplyServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_RebindBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebindServiceBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).RebindBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceService_RebindBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).RebindBackend(ctx, req.(*RebindServiceBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchServicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServiceServer).Watch(m, &grpc.GenericServerStream[WatchServicesRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceService_WatchServer = grpc.ServerStreamingServer[WatchEvent]

// ServiceService_ServiceDesc is the grpc.ServiceDesc for ServiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "falak.api.v1alpha1.ServiceService",
	HandlerType: (*ServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ServiceService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ServiceService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ServiceService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ServiceService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ServiceService_Delete_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _ServiceService_Apply_Handler,
		},
		{
			MethodName: "RebindBackend",
			Handler:    _ServiceService_RebindBackend_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _ServiceService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/v1alpha1/service_service.proto",
}
