// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1alpha1/system_service.proto

package v1alpha1pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoRequest) Reset() {
	*x = SystemInfoRequest{}
	mi := &file_api_proto_v1alpha1_system_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoRequest) ProtoMessage() {}

func (x *SystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_system_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoRequest.ProtoReflect.Descriptor instead.
func (*SystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_system_service_proto_rawDescGZIP(), []int{0}
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_api_proto_v1alpha1_system_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_system_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_system_service_proto_rawDescGZIP(), []int{1}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GoVersion     string                 `protobuf:"bytes,2,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_api_proto_v1alpha1_system_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_system_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_system_service_proto_rawDescGZIP(), []int{2}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *VersionResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_api_proto_v1alpha1_system_service_proto protoreflect.FileDescriptor

const file_api_proto_v1alpha1_system_service_proto_rawDesc = "" +
	"\n" +
	"'api/proto/v1alpha1/system_service.proto\x12\x12falak.api.v1alpha1\x1a\x1fapi/proto/v1alpha1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\x13\n" +
	"\x11SystemInfoRequest\"\x10\n" +
	"\x0eVersionRequest\"f\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"go_version\x18\x02 \x01(\tR\tgoVersion\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform2\xf3\x01\n" +
	"\rSystemService\x12l\n" +
	"\x04Info\x12%.falak.api.v1alpha1.SystemInfoRequest\x1a\x1e.falak.api.v1alpha1.SystemInfo\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1alpha1/system/info\x12t\n" +
	"\aVersion\x12\".falak.api.v1alpha1.VersionRequest\x1a#.falak.api.v1alpha1.VersionResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1alpha1/system/versionB2Z0github.com/tareksalem/falak/api/proto/v1alpha1pbb\x06proto3"

var (
	file_api_proto_v1alpha1_system_service_proto_rawDescOnce sync.Once
	file_api_proto_v1alpha1_system_service_proto_rawDescData []byte
)

func file_api_proto_v1alpha1_system_service_proto_rawDescGZIP() []byte {
	file_api_proto_v1alpha1_system_service_proto_rawDescOnce.Do(func() {
		file_api_proto_v1alpha1_system_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_system_service_proto_rawDesc), len(file_api_proto_v1alpha1_system_service_proto_rawDesc)))
	})
	return file_api_proto_v1alpha1_system_service_proto_rawDescData
}

var file_api_proto_v1alpha1_system_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_v1alpha1_system_service_proto_goTypes = []any{
	(*SystemInfoRequest)(nil), // 0: falak.api.v1alpha1.SystemInfoRequest
	(*VersionRequest)(nil),    // 1: falak.api.v1alpha1.VersionRequest
	(*VersionResponse)(nil),   // 2: falak.api.v1alpha1.VersionResponse
	(*SystemInfo)(nil),        // 3: falak.api.v1alpha1.SystemInfo
}
var file_api_proto_v1alpha1_system_service_proto_depIdxs = []int32{
	0, // 0: falak.api.v1alpha1.SystemService.Info:input_type -> falak.api.v1alpha1.SystemInfoRequest
	1, // 1: falak.api.v1alpha1.SystemService.Version:input_type -> falak.api.v1alpha1.VersionRequest
	3, // 2: falak.api.v1alpha1.SystemService.Info:output_type -> falak.api.v1alpha1.SystemInfo
	2, // 3: falak.api.v1alpha1.SystemService.Version:output_type -> falak.api.v1alpha1.VersionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1alpha1_system_service_proto_init() }
func file_api_proto_v1alpha1_system_service_proto_init() {
	if File_api_proto_v1alpha1_system_service_proto != nil {
		return
	}
	file_api_proto_v1alpha1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_system_service_proto_rawDesc), len(file_api_proto_v1alpha1_system_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1alpha1_system_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1alpha1_system_service_proto_depIdxs,
		MessageInfos:      file_api_proto_v1alpha1_system_service_proto_msgTypes,
	}.Build()
	File_api_proto_v1alpha1_system_service_proto = out.File
	file_api_proto_v1alpha1_system_service_proto_goTypes = nil
	file_api_proto_v1alpha1_system_service_proto_depIdxs = nil
}
