# .air.toml - Configuration for Falak monorepo
root = "."
tmp_dir = "tmp"

[build]
# Build the specific entry point in the monorepo
cmd = "go work sync && go build -o ./tmp/main ./cmd/main.go"
bin = "tmp/main"
# Pass any command line arguments from air to the app
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "dev"]
include_dir = ["cmd", "internal"]
kill_delay = 500
# Add this to ensure Go workspace dependencies work correctly
env = ["GO111MODULE=on", "GOWORK=go.work"]

[log]
time = true

[color]
main = "cyan"
watcher = "yellow"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true