// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: service.proto

package servicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service is the gossip-wire representation of a Falak Service.
// Mirrors service.Service in service/service.go.
type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Spec          *ServiceSpec           `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	BackendStates []*BackendState        `protobuf:"bytes,8,rep,name=backend_states,json=backendStates,proto3" json:"backend_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Service) GetSpec() *ServiceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Service) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Service) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Service) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Service) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Service) GetBackendStates() []*BackendState {
	if x != nil {
		return x.BackendStates
	}
	return nil
}

// ServiceSpec mirrors service.ServiceSpec.
type ServiceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Visibility    string                 `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Ports         []*ServicePort         `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	Backends      []*ServiceBackend      `protobuf:"bytes,5,rep,name=backends,proto3" json:"backends,omitempty"`
	Strategy      *Strategy              `protobuf:"bytes,6,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Timeouts      *ServiceTimeouts       `protobuf:"bytes,7,opt,name=timeouts,proto3" json:"timeouts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSpec) Reset() {
	*x = ServiceSpec{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSpec) ProtoMessage() {}

func (x *ServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSpec.ProtoReflect.Descriptor instead.
func (*ServiceSpec) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceSpec) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ServiceSpec) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ServiceSpec) GetPorts() []*ServicePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ServiceSpec) GetBackends() []*ServiceBackend {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *ServiceSpec) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *ServiceSpec) GetTimeouts() *ServiceTimeouts {
	if x != nil {
		return x.Timeouts
	}
	return nil
}

// ServicePort mirrors service.ServicePort.
type ServicePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePort) Reset() {
	*x = ServicePort{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePort) ProtoMessage() {}

func (x *ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePort.ProtoReflect.Descriptor instead.
func (*ServicePort) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicePort) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServicePort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// ServiceBackend mirrors service.ServiceBackend.
type ServiceBackend struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Capsule           string                 `protobuf:"bytes,1,opt,name=capsule,proto3" json:"capsule,omitempty"`
	CapturedCapsuleId string                 `protobuf:"bytes,2,opt,name=captured_capsule_id,json=capturedCapsuleId,proto3" json:"captured_capsule_id,omitempty"`
	PortMap           map[string]string      `protobuf:"bytes,3,rep,name=port_map,json=portMap,proto3" json:"port_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Weight            int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServiceBackend) Reset() {
	*x = ServiceBackend{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceBackend) ProtoMessage() {}

func (x *ServiceBackend) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceBackend.ProtoReflect.Descriptor instead.
func (*ServiceBackend) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceBackend) GetCapsule() string {
	if x != nil {
		return x.Capsule
	}
	return ""
}

func (x *ServiceBackend) GetCapturedCapsuleId() string {
	if x != nil {
		return x.CapturedCapsuleId
	}
	return ""
}

func (x *ServiceBackend) GetPortMap() map[string]string {
	if x != nil {
		return x.PortMap
	}
	return nil
}

func (x *ServiceBackend) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// Strategy mirrors service.Strategy.
type Strategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Canary        *CanaryStrategy        `protobuf:"bytes,2,opt,name=canary,proto3" json:"canary,omitempty"`
	BlueGreen     *BlueGreenStrategy     `protobuf:"bytes,3,opt,name=blue_green,json=blueGreen,proto3" json:"blue_green,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Strategy) Reset() {
	*x = Strategy{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strategy) ProtoMessage() {}

func (x *Strategy) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strategy.ProtoReflect.Descriptor instead.
func (*Strategy) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *Strategy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Strategy) GetCanary() *CanaryStrategy {
	if x != nil {
		return x.Canary
	}
	return nil
}

func (x *Strategy) GetBlueGreen() *BlueGreenStrategy {
	if x != nil {
		return x.BlueGreen
	}
	return nil
}

// CanaryStrategy mirrors service.CanaryStrategy. Interval is seconds.
type CanaryStrategy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Target          string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	From            string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Step            int32                  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	SuccessCriteria []string               `protobuf:"bytes,5,rep,name=success_criteria,json=successCriteria,proto3" json:"success_criteria,omitempty"`
	AbortOn         []string               `protobuf:"bytes,6,rep,name=abort_on,json=abortOn,proto3" json:"abort_on,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CanaryStrategy) Reset() {
	*x = CanaryStrategy{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanaryStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanaryStrategy) ProtoMessage() {}

func (x *CanaryStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanaryStrategy.ProtoReflect.Descriptor instead.
func (*CanaryStrategy) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *CanaryStrategy) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CanaryStrategy) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CanaryStrategy) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *CanaryStrategy) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *CanaryStrategy) GetSuccessCriteria() []string {
	if x != nil {
		return x.SuccessCriteria
	}
	return nil
}

func (x *CanaryStrategy) GetAbortOn() []string {
	if x != nil {
		return x.AbortOn
	}
	return nil
}

// BlueGreenStrategy mirrors service.BlueGreenStrategy. Drain is seconds.
type BlueGreenStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        string                 `protobuf:"bytes,1,opt,name=active,proto3" json:"active,omitempty"`
	DrainSeconds  int32                  `protobuf:"varint,2,opt,name=drain_seconds,json=drainSeconds,proto3" json:"drain_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlueGreenStrategy) Reset() {
	*x = BlueGreenStrategy{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlueGreenStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlueGreenStrategy) ProtoMessage() {}

func (x *BlueGreenStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlueGreenStrategy.ProtoReflect.Descriptor instead.
func (*BlueGreenStrategy) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *BlueGreenStrategy) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

func (x *BlueGreenStrategy) GetDrainSeconds() int32 {
	if x != nil {
		return x.DrainSeconds
	}
	return 0
}

// ServiceTimeouts mirrors service.ServiceTimeouts. Values are seconds.
type ServiceTimeouts struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdleSeconds    int32                  `protobuf:"varint,1,opt,name=idle_seconds,json=idleSeconds,proto3" json:"idle_seconds,omitempty"`
	ConnectSeconds int32                  `protobuf:"varint,2,opt,name=connect_seconds,json=connectSeconds,proto3" json:"connect_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceTimeouts) Reset() {
	*x = ServiceTimeouts{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTimeouts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTimeouts) ProtoMessage() {}

func (x *ServiceTimeouts) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTimeouts.ProtoReflect.Descriptor instead.
func (*ServiceTimeouts) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceTimeouts) GetIdleSeconds() int32 {
	if x != nil {
		return x.IdleSeconds
	}
	return 0
}

func (x *ServiceTimeouts) GetConnectSeconds() int32 {
	if x != nil {
		return x.ConnectSeconds
	}
	return 0
}

// BackendState mirrors service.BackendState. The "name" field is the
// backend's capsule name (matching ServiceBackend.capsule).
type BackendState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Resolution        string                 `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	CapturedCapsuleId string                 `protobuf:"bytes,3,opt,name=captured_capsule_id,json=capturedCapsuleId,proto3" json:"captured_capsule_id,omitempty"`
	LastResolvedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_resolved_at,json=lastResolvedAt,proto3" json:"last_resolved_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BackendState) Reset() {
	*x = BackendState{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendState) ProtoMessage() {}

func (x *BackendState) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendState.ProtoReflect.Descriptor instead.
func (*BackendState) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *BackendState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendState) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *BackendState) GetCapturedCapsuleId() string {
	if x != nil {
		return x.CapturedCapsuleId
	}
	return ""
}

func (x *BackendState) GetLastResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastResolvedAt
	}
	return nil
}

// ServiceUpdate is the gossip payload announcing a Service create/update.
type ServiceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	SenderNodeId  string                 `protobuf:"bytes,2,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUpdate) Reset() {
	*x = ServiceUpdate{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdate) ProtoMessage() {}

func (x *ServiceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdate.ProtoReflect.Descriptor instead.
func (*ServiceUpdate) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceUpdate) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceUpdate) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

// ServiceWithdrawal is the gossip payload announcing a Service deletion.
type ServiceWithdrawal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	SenderNodeId  string                 `protobuf:"bytes,2,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceWithdrawal) Reset() {
	*x = ServiceWithdrawal{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceWithdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceWithdrawal) ProtoMessage() {}

func (x *ServiceWithdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceWithdrawal.ProtoReflect.Descriptor instead.
func (*ServiceWithdrawal) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceWithdrawal) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceWithdrawal) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

// Envelope is the signed wrapper for every Service-gossip message.
// type is "update" or "withdrawal"; payload is the marshaled inner
// message. Signature covers a canonical length-prefixed concatenation
// of (type, payload, sender_id, timestamp).
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Envelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\rfalak.service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12.\n" +
	"\x04spec\x18\x03 \x01(\v2\x1a.falak.service.ServiceSpecR\x04spec\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12B\n" +
	"\x0ebackend_states\x18\b \x03(\v2\x1b.falak.service.BackendStateR\rbackendStates\"\xb5\x02\n" +
	"\vServiceSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"visibility\x18\x02 \x01(\tR\n" +
	"visibility\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x120\n" +
	"\x05ports\x18\x04 \x03(\v2\x1a.falak.service.ServicePortR\x05ports\x129\n" +
	"\bbackends\x18\x05 \x03(\v2\x1d.falak.service.ServiceBackendR\bbackends\x123\n" +
	"\bstrategy\x18\x06 \x01(\v2\x17.falak.service.StrategyR\bstrategy\x12:\n" +
	"\btimeouts\x18\a \x01(\v2\x1e.falak.service.ServiceTimeoutsR\btimeouts\"Q\n" +
	"\vServicePort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xf5\x01\n" +
	"\x0eServiceBackend\x12\x18\n" +
	"\acapsule\x18\x01 \x01(\tR\acapsule\x12.\n" +
	"\x13captured_capsule_id\x18\x02 \x01(\tR\x11capturedCapsuleId\x12E\n" +
	"\bport_map\x18\x03 \x03(\v2*.falak.service.ServiceBackend.PortMapEntryR\aportMap\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x1a:\n" +
	"\fPortMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\bStrategy\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x125\n" +
	"\x06canary\x18\x02 \x01(\v2\x1d.falak.service.CanaryStrategyR\x06canary\x12?\n" +
	"\n" +
	"blue_green\x18\x03 \x01(\v2 .falak.service.BlueGreenStrategyR\tblueGreen\"\xc1\x01\n" +
	"\x0eCanaryStrategy\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x05R\x04step\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\x05R\x0fintervalSeconds\x12)\n" +
	"\x10success_criteria\x18\x05 \x03(\tR\x0fsuccessCriteria\x12\x19\n" +
	"\babort_on\x18\x06 \x03(\tR\aabortOn\"P\n" +
	"\x11BlueGreenStrategy\x12\x16\n" +
	"\x06active\x18\x01 \x01(\tR\x06active\x12#\n" +
	"\rdrain_seconds\x18\x02 \x01(\x05R\fdrainSeconds\"]\n" +
	"\x0fServiceTimeouts\x12!\n" +
	"\fidle_seconds\x18\x01 \x01(\x05R\vidleSeconds\x12'\n" +
	"\x0fconnect_seconds\x18\x02 \x01(\x05R\x0econnectSeconds\"\xb8\x01\n" +
	"\fBackendState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12.\n" +
	"\x13captured_capsule_id\x18\x03 \x01(\tR\x11capturedCapsuleId\x12D\n" +
	"\x10last_resolved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastResolvedAt\"g\n" +
	"\rServiceUpdate\x120\n" +
	"\aservice\x18\x01 \x01(\v2\x16.falak.service.ServiceR\aservice\x12$\n" +
	"\x0esender_node_id\x18\x02 \x01(\tR\fsenderNodeId\"X\n" +
	"\x11ServiceWithdrawal\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12$\n" +
	"\x0esender_node_id\x18\x02 \x01(\tR\fsenderNodeId\"\xad\x01\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignatureB5Z3github.com/tareksalem/falak/service/proto/servicepbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_service_proto_goTypes = []any{
	(*Service)(nil),               // 0: falak.service.Service
	(*ServiceSpec)(nil),           // 1: falak.service.ServiceSpec
	(*ServicePort)(nil),           // 2: falak.service.ServicePort
	(*ServiceBackend)(nil),        // 3: falak.service.ServiceBackend
	(*Strategy)(nil),              // 4: falak.service.Strategy
	(*CanaryStrategy)(nil),        // 5: falak.service.CanaryStrategy
	(*BlueGreenStrategy)(nil),     // 6: falak.service.BlueGreenStrategy
	(*ServiceTimeouts)(nil),       // 7: falak.service.ServiceTimeouts
	(*BackendState)(nil),          // 8: falak.service.BackendState
	(*ServiceUpdate)(nil),         // 9: falak.service.ServiceUpdate
	(*ServiceWithdrawal)(nil),     // 10: falak.service.ServiceWithdrawal
	(*Envelope)(nil),              // 11: falak.service.Envelope
	nil,                           // 12: falak.service.ServiceBackend.PortMapEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	1,  // 0: falak.service.Service.spec:type_name -> falak.service.ServiceSpec
	13, // 1: falak.service.Service.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: falak.service.Service.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 3: falak.service.Service.backend_states:type_name -> falak.service.BackendState
	2,  // 4: falak.service.ServiceSpec.ports:type_name -> falak.service.ServicePort
	3,  // 5: falak.service.ServiceSpec.backends:type_name -> falak.service.ServiceBackend
	4,  // 6: falak.service.ServiceSpec.strategy:type_name -> falak.service.Strategy
	7,  // 7: falak.service.ServiceSpec.timeouts:type_name -> falak.service.ServiceTimeouts
	12, // 8: falak.service.ServiceBackend.port_map:type_name -> falak.service.ServiceBackend.PortMapEntry
	5,  // 9: falak.service.Strategy.canary:type_name -> falak.service.CanaryStrategy
	6,  // 10: falak.service.Strategy.blue_green:type_name -> falak.service.BlueGreenStrategy
	13, // 11: falak.service.BackendState.last_resolved_at:type_name -> google.protobuf.Timestamp
	0,  // 12: falak.service.ServiceUpdate.service:type_name -> falak.service.Service
	13, // 13: falak.service.Envelope.timestamp:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
