// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sync.proto

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncRequest is sent to request member list synchronization
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterPath   string                 `protobuf:"bytes,1,opt,name=cluster_path,json=clusterPath,proto3" json:"cluster_path,omitempty"`      // Cluster to sync
	LastSyncTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"` // nil for full sync, set for delta sync
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`            // For correlation
	MaxMembers    int32                  `protobuf:"varint,4,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"`        // Pagination limit (0 = no limit)
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`                                   // For pagination continuation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetClusterPath() string {
	if x != nil {
		return x.ClusterPath
	}
	return ""
}

func (x *SyncRequest) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

func (x *SyncRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncRequest) GetMaxMembers() int32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *SyncRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// SyncResponse contains the member list and revocations
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`     // Correlation with request
	Members       []*MemberInfo          `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`                          // Member list
	SyncTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`        // Use as last_sync_time next time
	IsComplete    bool                   `protobuf:"varint,4,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"` // False if more pages available
	NextCursor    string                 `protobuf:"bytes,5,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`  // For pagination continuation
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                              // Error message if sync failed
	Revocations   []*RevocationEntry     `protobuf:"bytes,7,rep,name=revocations,proto3" json:"revocations,omitempty"`                  // Certificate revocations to merge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncResponse) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *SyncResponse) GetSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncTime
	}
	return nil
}

func (x *SyncResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *SyncResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *SyncResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SyncResponse) GetRevocations() []*RevocationEntry {
	if x != nil {
		return x.Revocations
	}
	return nil
}

// SyncPush actively delivers a single newly-admitted member to an existing
// peer (Layer 1 of the O13 join-convergence design). Unlike SyncRequest /
// SyncResponse (pull), this is a push initiated by the voucher's fan-out so
// existing members learn about a new node without waiting for the best-effort
// Step-2 PubSub broadcast or the periodic anti-entropy tail. The receiver
// verifies the sender is an authenticated peer (same phonebook.Exists gate as
// SyncRequest) and inserts the member via the idempotent processMember path.
type SyncPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterPath   string                 `protobuf:"bytes,1,opt,name=cluster_path,json=clusterPath,proto3" json:"cluster_path,omitempty"` // Cluster the member belongs to
	Member        *MemberInfo            `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`                              // The newly-admitted member to insert
	PushId        string                 `protobuf:"bytes,3,opt,name=push_id,json=pushId,proto3" json:"push_id,omitempty"`                // For correlation / logging
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPush) Reset() {
	*x = SyncPush{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPush) ProtoMessage() {}

func (x *SyncPush) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPush.ProtoReflect.Descriptor instead.
func (*SyncPush) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncPush) GetClusterPath() string {
	if x != nil {
		return x.ClusterPath
	}
	return ""
}

func (x *SyncPush) GetMember() *MemberInfo {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *SyncPush) GetPushId() string {
	if x != nil {
		return x.PushId
	}
	return ""
}

// SyncPushAck acknowledges a SyncPush.
type SyncPushAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushId        string                 `protobuf:"bytes,1,opt,name=push_id,json=pushId,proto3" json:"push_id,omitempty"` // Correlation with the push
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`          // True if the member was inserted/updated
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                 // Non-empty on rejection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPushAck) Reset() {
	*x = SyncPushAck{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPushAck) ProtoMessage() {}

func (x *SyncPushAck) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPushAck.ProtoReflect.Descriptor instead.
func (*SyncPushAck) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncPushAck) GetPushId() string {
	if x != nil {
		return x.PushId
	}
	return ""
}

func (x *SyncPushAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SyncPushAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RevocationEntry describes a revoked certificate
type RevocationEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CertFingerprint string                 `protobuf:"bytes,1,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"` // SHA-256 of the certificate bytes
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                            // Node whose cert was revoked
	ClusterPath     string                 `protobuf:"bytes,3,opt,name=cluster_path,json=clusterPath,proto3" json:"cluster_path,omitempty"`             // Cluster this applies to
	RevokedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	Reason          string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	RevokedBy       string                 `protobuf:"bytes,6,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"` // Node that initiated the revocation
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RevocationEntry) Reset() {
	*x = RevocationEntry{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevocationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevocationEntry) ProtoMessage() {}

func (x *RevocationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevocationEntry.ProtoReflect.Descriptor instead.
func (*RevocationEntry) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

func (x *RevocationEntry) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

func (x *RevocationEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RevocationEntry) GetClusterPath() string {
	if x != nil {
		return x.ClusterPath
	}
	return ""
}

func (x *RevocationEntry) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *RevocationEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevocationEntry) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

// MemberInfo describes a cluster member (extended version for sync)
type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Capabilities  *Capabilities          `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // active, suspected, quarantined, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

func (x *MemberInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MemberInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *MemberInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MemberInfo) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *MemberInfo) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *MemberInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *MemberInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Capabilities describes a node's resources and features
type Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskGb        int64                  `protobuf:"varint,3,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	Datacenter    string                 `protobuf:"bytes,4,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *Capabilities) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Capabilities) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *Capabilities) GetDiskGb() int64 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *Capabilities) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *Capabilities) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Capabilities) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\n" +
	"falak.sync\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n" +
	"\vSyncRequest\x12!\n" +
	"\fcluster_path\x18\x01 \x01(\tR\vclusterPath\x12@\n" +
	"\x0elast_sync_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x1f\n" +
	"\vmax_members\x18\x04 \x01(\x05R\n" +
	"maxMembers\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"\xaf\x02\n" +
	"\fSyncResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x120\n" +
	"\amembers\x18\x02 \x03(\v2\x16.falak.sync.MemberInfoR\amembers\x127\n" +
	"\tsync_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncTime\x12\x1f\n" +
	"\vis_complete\x18\x04 \x01(\bR\n" +
	"isComplete\x12\x1f\n" +
	"\vnext_cursor\x18\x05 \x01(\tR\n" +
	"nextCursor\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12=\n" +
	"\vrevocations\x18\a \x03(\v2\x1b.falak.sync.RevocationEntryR\vrevocations\"v\n" +
	"\bSyncPush\x12!\n" +
	"\fcluster_path\x18\x01 \x01(\tR\vclusterPath\x12.\n" +
	"\x06member\x18\x02 \x01(\v2\x16.falak.sync.MemberInfoR\x06member\x12\x17\n" +
	"\apush_id\x18\x03 \x01(\tR\x06pushId\"X\n" +
	"\vSyncPushAck\x12\x17\n" +
	"\apush_id\x18\x01 \x01(\tR\x06pushId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xea\x01\n" +
	"\x0fRevocationEntry\x12)\n" +
	"\x10cert_fingerprint\x18\x01 \x01(\tR\x0fcertFingerprint\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\fcluster_path\x18\x03 \x01(\tR\vclusterPath\x129\n" +
	"\n" +
	"revoked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x06 \x01(\tR\trevokedBy\"\xaa\x02\n" +
	"\n" +
	"MemberInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12<\n" +
	"\fcapabilities\x18\x04 \x01(\v2\x18.falak.sync.CapabilitiesR\fcapabilities\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\x96\x02\n" +
	"\fCapabilities\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\x12\x17\n" +
	"\adisk_gb\x18\x03 \x01(\x03R\x06diskGb\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x04 \x01(\tR\n" +
	"datacenter\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12B\n" +
	"\bmetadata\x18\x06 \x03(\v2&.falak.sync.Capabilities.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-github.com/tareksalem/falak/node/proto/syncpbb\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sync_proto_goTypes = []any{
	(*SyncRequest)(nil),           // 0: falak.sync.SyncRequest
	(*SyncResponse)(nil),          // 1: falak.sync.SyncResponse
	(*SyncPush)(nil),              // 2: falak.sync.SyncPush
	(*SyncPushAck)(nil),           // 3: falak.sync.SyncPushAck
	(*RevocationEntry)(nil),       // 4: falak.sync.RevocationEntry
	(*MemberInfo)(nil),            // 5: falak.sync.MemberInfo
	(*Capabilities)(nil),          // 6: falak.sync.Capabilities
	nil,                           // 7: falak.sync.Capabilities.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_sync_proto_depIdxs = []int32{
	8,  // 0: falak.sync.SyncRequest.last_sync_time:type_name -> google.protobuf.Timestamp
	5,  // 1: falak.sync.SyncResponse.members:type_name -> falak.sync.MemberInfo
	8,  // 2: falak.sync.SyncResponse.sync_time:type_name -> google.protobuf.Timestamp
	4,  // 3: falak.sync.SyncResponse.revocations:type_name -> falak.sync.RevocationEntry
	5,  // 4: falak.sync.SyncPush.member:type_name -> falak.sync.MemberInfo
	8,  // 5: falak.sync.RevocationEntry.revoked_at:type_name -> google.protobuf.Timestamp
	6,  // 6: falak.sync.MemberInfo.capabilities:type_name -> falak.sync.Capabilities
	8,  // 7: falak.sync.MemberInfo.joined_at:type_name -> google.protobuf.Timestamp
	8,  // 8: falak.sync.MemberInfo.last_seen:type_name -> google.protobuf.Timestamp
	7,  // 9: falak.sync.Capabilities.metadata:type_name -> falak.sync.Capabilities.MetadataEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
