// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: health.proto

package healthpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeStatus represents the health status of a node
type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_ACTIVE      NodeStatus = 1 // Healthy, score 0-4
	NodeStatus_NODE_STATUS_SUSPECTED   NodeStatus = 2 // Score 4-10, being watched
	NodeStatus_NODE_STATUS_QUARANTINED NodeStatus = 3 // Score >= 10, isolated
	NodeStatus_NODE_STATUS_FAILED      NodeStatus = 4 // Confirmed dead, removed
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ACTIVE",
		2: "NODE_STATUS_SUSPECTED",
		3: "NODE_STATUS_QUARANTINED",
		4: "NODE_STATUS_FAILED",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ACTIVE":      1,
		"NODE_STATUS_SUSPECTED":   2,
		"NODE_STATUS_QUARANTINED": 3,
		"NODE_STATUS_FAILED":      4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_health_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_health_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

// Ping is sent from prober to target via direct stream
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    string                 `protobuf:"bytes,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"` // Prober's node ID
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`                        // Unique sequence number (unix nano)
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *Ping) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Ping) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Ack is the response to a Ping
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    string                 `protobuf:"bytes,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"` // Target's node ID (responder)
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`                        // Must match Ping.sequence
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *Ack) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Ack) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HealthMessage is the envelope for all health-related PubSub messages
type HealthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                         // "score_update", "ping_request", "threshold_crossed"
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                   // Serialized message based on type
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // Node that published this message
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // Signature over (type + payload + sender_id + timestamp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthMessage) Reset() {
	*x = HealthMessage{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthMessage) ProtoMessage() {}

func (x *HealthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthMessage.ProtoReflect.Descriptor instead.
func (*HealthMessage) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

func (x *HealthMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HealthMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *HealthMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// ScoreUpdate is published on every score change
type ScoreUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"` // Node this score is about
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`                                   // Current reliability score
	Alive         bool                   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`                                    // If true, target responded, score = 0
	UpdatedBy     string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`            // Node that published this update
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"` // "direct_ping_fail", "indirect_ping_fail", "probe_success", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreUpdate) Reset() {
	*x = ScoreUpdate{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreUpdate) ProtoMessage() {}

func (x *ScoreUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreUpdate.ProtoReflect.Descriptor instead.
func (*ScoreUpdate) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreUpdate) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *ScoreUpdate) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreUpdate) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *ScoreUpdate) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *ScoreUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ScoreUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PingRequest is published when direct ping fails, asking others to probe
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"` // Node to ping
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`      // Node requesting the probe
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`            // Unique ID for this request (UUID)
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *PingRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *PingRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PingRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ThresholdCrossed is published when a node's score crosses quarantine threshold
type ThresholdCrossed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"` // Node that crossed threshold
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`                                   // Current score
	ReportedBy    string                 `protobuf:"bytes,3,opt,name=reported_by,json=reportedBy,proto3" json:"reported_by,omitempty"`         // Node that detected the crossing
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThresholdCrossed) Reset() {
	*x = ThresholdCrossed{}
	mi := &file_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdCrossed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdCrossed) ProtoMessage() {}

func (x *ThresholdCrossed) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdCrossed.ProtoReflect.Descriptor instead.
func (*ThresholdCrossed) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{5}
}

func (x *ThresholdCrossed) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *ThresholdCrossed) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ThresholdCrossed) GetReportedBy() string {
	if x != nil {
		return x.ReportedBy
	}
	return ""
}

func (x *ThresholdCrossed) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ResourceUpdate is published periodically by every node with the latest
// snapshot of host-level resource utilization. Carried inside the
// HealthMessage envelope (type = "resource_update").
type ResourceUpdate struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	NodeId     string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Node the snapshot belongs to (== HealthMessage.sender_id)
	CapturedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	// CPU
	CpuCores       int32   `protobuf:"varint,10,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuUsedPercent float64 `protobuf:"fixed64,11,opt,name=cpu_used_percent,json=cpuUsedPercent,proto3" json:"cpu_used_percent,omitempty"`
	// Memory (megabytes)
	MemoryTotalMb     int64   `protobuf:"varint,20,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	MemoryAvailableMb int64   `protobuf:"varint,21,opt,name=memory_available_mb,json=memoryAvailableMb,proto3" json:"memory_available_mb,omitempty"`
	MemoryUsedMb      int64   `protobuf:"varint,22,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	MemoryUsedPercent float64 `protobuf:"fixed64,23,opt,name=memory_used_percent,json=memoryUsedPercent,proto3" json:"memory_used_percent,omitempty"`
	// Disk (megabytes; primary volume)
	DiskTotalMb     int64   `protobuf:"varint,30,opt,name=disk_total_mb,json=diskTotalMb,proto3" json:"disk_total_mb,omitempty"`
	DiskFreeMb      int64   `protobuf:"varint,31,opt,name=disk_free_mb,json=diskFreeMb,proto3" json:"disk_free_mb,omitempty"`
	DiskUsedMb      int64   `protobuf:"varint,32,opt,name=disk_used_mb,json=diskUsedMb,proto3" json:"disk_used_mb,omitempty"`
	DiskUsedPercent float64 `protobuf:"fixed64,33,opt,name=disk_used_percent,json=diskUsedPercent,proto3" json:"disk_used_percent,omitempty"`
	// Load averages (1m, 5m, 15m)
	LoadOne     float64 `protobuf:"fixed64,40,opt,name=load_one,json=loadOne,proto3" json:"load_one,omitempty"`
	LoadFive    float64 `protobuf:"fixed64,41,opt,name=load_five,json=loadFive,proto3" json:"load_five,omitempty"`
	LoadFifteen float64 `protobuf:"fixed64,42,opt,name=load_fifteen,json=loadFifteen,proto3" json:"load_fifteen,omitempty"`
	// Network throughput (bytes per second, aggregated across interfaces)
	NetSentBytesPerSec int64 `protobuf:"varint,50,opt,name=net_sent_bytes_per_sec,json=netSentBytesPerSec,proto3" json:"net_sent_bytes_per_sec,omitempty"`
	NetRecvBytesPerSec int64 `protobuf:"varint,51,opt,name=net_recv_bytes_per_sec,json=netRecvBytesPerSec,proto3" json:"net_recv_bytes_per_sec,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResourceUpdate) Reset() {
	*x = ResourceUpdate{}
	mi := &file_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUpdate) ProtoMessage() {}

func (x *ResourceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUpdate.ProtoReflect.Descriptor instead.
func (*ResourceUpdate) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ResourceUpdate) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

func (x *ResourceUpdate) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceUpdate) GetCpuUsedPercent() float64 {
	if x != nil {
		return x.CpuUsedPercent
	}
	return 0
}

func (x *ResourceUpdate) GetMemoryTotalMb() int64 {
	if x != nil {
		return x.MemoryTotalMb
	}
	return 0
}

func (x *ResourceUpdate) GetMemoryAvailableMb() int64 {
	if x != nil {
		return x.MemoryAvailableMb
	}
	return 0
}

func (x *ResourceUpdate) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *ResourceUpdate) GetMemoryUsedPercent() float64 {
	if x != nil {
		return x.MemoryUsedPercent
	}
	return 0
}

func (x *ResourceUpdate) GetDiskTotalMb() int64 {
	if x != nil {
		return x.DiskTotalMb
	}
	return 0
}

func (x *ResourceUpdate) GetDiskFreeMb() int64 {
	if x != nil {
		return x.DiskFreeMb
	}
	return 0
}

func (x *ResourceUpdate) GetDiskUsedMb() int64 {
	if x != nil {
		return x.DiskUsedMb
	}
	return 0
}

func (x *ResourceUpdate) GetDiskUsedPercent() float64 {
	if x != nil {
		return x.DiskUsedPercent
	}
	return 0
}

func (x *ResourceUpdate) GetLoadOne() float64 {
	if x != nil {
		return x.LoadOne
	}
	return 0
}

func (x *ResourceUpdate) GetLoadFive() float64 {
	if x != nil {
		return x.LoadFive
	}
	return 0
}

func (x *ResourceUpdate) GetLoadFifteen() float64 {
	if x != nil {
		return x.LoadFifteen
	}
	return 0
}

func (x *ResourceUpdate) GetNetSentBytesPerSec() int64 {
	if x != nil {
		return x.NetSentBytesPerSec
	}
	return 0
}

func (x *ResourceUpdate) GetNetRecvBytesPerSec() int64 {
	if x != nil {
		return x.NetRecvBytesPerSec
	}
	return 0
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\ffalak.health\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\x04Ping\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\tR\n" +
	"fromNodeId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"}\n" +
	"\x03Ack\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\tR\n" +
	"fromNodeId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb2\x01\n" +
	"\rHealthMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xd0\x01\n" +
	"\vScoreUpdate\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x14\n" +
	"\x05alive\x18\x03 \x01(\bR\x05alive\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\xaf\x01\n" +
	"\vPingRequest\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa9\x01\n" +
	"\x10ThresholdCrossed\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1f\n" +
	"\vreported_by\x18\x03 \x01(\tR\n" +
	"reportedBy\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb2\x05\n" +
	"\x0eResourceUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12;\n" +
	"\vcaptured_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\x12\x1b\n" +
	"\tcpu_cores\x18\n" +
	" \x01(\x05R\bcpuCores\x12(\n" +
	"\x10cpu_used_percent\x18\v \x01(\x01R\x0ecpuUsedPercent\x12&\n" +
	"\x0fmemory_total_mb\x18\x14 \x01(\x03R\rmemoryTotalMb\x12.\n" +
	"\x13memory_available_mb\x18\x15 \x01(\x03R\x11memoryAvailableMb\x12$\n" +
	"\x0ememory_used_mb\x18\x16 \x01(\x03R\fmemoryUsedMb\x12.\n" +
	"\x13memory_used_percent\x18\x17 \x01(\x01R\x11memoryUsedPercent\x12\"\n" +
	"\rdisk_total_mb\x18\x1e \x01(\x03R\vdiskTotalMb\x12 \n" +
	"\fdisk_free_mb\x18\x1f \x01(\x03R\n" +
	"diskFreeMb\x12 \n" +
	"\fdisk_used_mb\x18  \x01(\x03R\n" +
	"diskUsedMb\x12*\n" +
	"\x11disk_used_percent\x18! \x01(\x01R\x0fdiskUsedPercent\x12\x19\n" +
	"\bload_one\x18( \x01(\x01R\aloadOne\x12\x1b\n" +
	"\tload_five\x18) \x01(\x01R\bloadFive\x12!\n" +
	"\fload_fifteen\x18* \x01(\x01R\vloadFifteen\x122\n" +
	"\x16net_sent_bytes_per_sec\x182 \x01(\x03R\x12netSentBytesPerSec\x122\n" +
	"\x16net_recv_bytes_per_sec\x183 \x01(\x03R\x12netRecvBytesPerSec*\x91\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15NODE_STATUS_SUSPECTED\x10\x02\x12\x1b\n" +
	"\x17NODE_STATUS_QUARANTINED\x10\x03\x12\x16\n" +
	"\x12NODE_STATUS_FAILED\x10\x04B1Z/github.com/tareksalem/falak/node/proto/healthpbb\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_health_proto_goTypes = []any{
	(NodeStatus)(0),               // 0: falak.health.NodeStatus
	(*Ping)(nil),                  // 1: falak.health.Ping
	(*Ack)(nil),                   // 2: falak.health.Ack
	(*HealthMessage)(nil),         // 3: falak.health.HealthMessage
	(*ScoreUpdate)(nil),           // 4: falak.health.ScoreUpdate
	(*PingRequest)(nil),           // 5: falak.health.PingRequest
	(*ThresholdCrossed)(nil),      // 6: falak.health.ThresholdCrossed
	(*ResourceUpdate)(nil),        // 7: falak.health.ResourceUpdate
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_health_proto_depIdxs = []int32{
	8, // 0: falak.health.Ping.timestamp:type_name -> google.protobuf.Timestamp
	8, // 1: falak.health.Ack.timestamp:type_name -> google.protobuf.Timestamp
	8, // 2: falak.health.HealthMessage.timestamp:type_name -> google.protobuf.Timestamp
	8, // 3: falak.health.ScoreUpdate.timestamp:type_name -> google.protobuf.Timestamp
	8, // 4: falak.health.PingRequest.timestamp:type_name -> google.protobuf.Timestamp
	8, // 5: falak.health.ThresholdCrossed.timestamp:type_name -> google.protobuf.Timestamp
	8, // 6: falak.health.ResourceUpdate.captured_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		EnumInfos:         file_health_proto_enumTypes,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
