// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: election.proto

package electionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ElectionMessage is the envelope for every election pubsub message.
// Following the same pattern as auth, health, and capsule orbit messages,
// it carries a type tag, a signed payload, and the sender identity.
type ElectionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                         // "claim" | "failed" | "group_claim"
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                   // Serialized Claim, ElectionFailed, or GroupClaim
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // Publishing node's libp2p peer ID
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // Over (type + payload + sender_id + timestamp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionMessage) Reset() {
	*x = ElectionMessage{}
	mi := &file_election_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionMessage) ProtoMessage() {}

func (x *ElectionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_election_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionMessage.ProtoReflect.Descriptor instead.
func (*ElectionMessage) Descriptor() ([]byte, []int) {
	return file_election_proto_rawDescGZIP(), []int{0}
}

func (x *ElectionMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ElectionMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ElectionMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ElectionMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ElectionMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Claim is broadcast by the elected node once its strategy decides it
// should run a capsule replica. The first node whose claim reaches the
// rest of the mesh becomes the winner, with deterministic tiebreak when
// multiple claims race.
//
// Tiebreak order when two Claim messages arrive for the same
// (capsule_id, replica_id):
//  1. Higher gravity_score wins.
//  2. Smaller offset_micros wins (deterministic priority delay; O14b).
//  3. Lexicographically smaller node_id wins.
//
// Both sides apply the same rule independently and converge on the
// same winner even when messages arrive in different orders. The
// tiebreak is fully clock-independent: offset_micros is the node's
// own computed publish delay (baseWait + slotDelay + jitter), not a
// wall-clock timestamp, so cross-node clock skew cannot reorder claims.
type Claim struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId       string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	ReplicaId       string                 `protobuf:"bytes,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	ClusterPath     string                 `protobuf:"bytes,3,opt,name=cluster_path,json=clusterPath,proto3" json:"cluster_path,omitempty"`
	NodeId          string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                             // Node claiming the replica
	GravityScore    float64                `protobuf:"fixed64,5,opt,name=gravity_score,json=gravityScore,proto3" json:"gravity_score,omitempty"`         // 0–100 percentage score
	TimestampMicros int64                  `protobuf:"varint,6,opt,name=timestamp_micros,json=timestampMicros,proto3" json:"timestamp_micros,omitempty"` // Claim creation time, microseconds since epoch (observability only; NOT the tiebreak)
	OffsetMicros    int64                  `protobuf:"varint,7,opt,name=offset_micros,json=offsetMicros,proto3" json:"offset_micros,omitempty"`          // Deterministic priority delay in microseconds; SMALLER wins the tiebreak (O14b)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_election_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_election_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_election_proto_rawDescGZIP(), []int{1}
}

func (x *Claim) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *Claim) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *Claim) GetClusterPath() string {
	if x != nil {
		return x.ClusterPath
	}
	return ""
}

func (x *Claim) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Claim) GetGravityScore() float64 {
	if x != nil {
		return x.GravityScore
	}
	return 0
}

func (x *Claim) GetTimestampMicros() int64 {
	if x != nil {
		return x.TimestampMicros
	}
	return 0
}

func (x *Claim) GetOffsetMicros() int64 {
	if x != nil {
		return x.OffsetMicros
	}
	return 0
}

// ElectionFailed is broadcast when any node concludes that no winner
// can be elected for a particular (capsule_id, replica_id). Every
// receiving node marks the capsule's replica as failed so the failure
// surfaces uniformly across the mesh.
type ElectionFailed struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId       string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	ReplicaId       string                 `protobuf:"bytes,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	ClusterPath     string                 `protobuf:"bytes,3,opt,name=cluster_path,json=clusterPath,proto3" json:"cluster_path,omitempty"`
	SenderId        string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                       // Node reporting the failure
	Reason          string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                           // Human-readable failure reason
	TimestampMicros int64                  `protobuf:"varint,6,opt,name=timestamp_micros,json=timestampMicros,proto3" json:"timestamp_micros,omitempty"` // Failure detection time
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ElectionFailed) Reset() {
	*x = ElectionFailed{}
	mi := &file_election_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionFailed) ProtoMessage() {}

func (x *ElectionFailed) ProtoReflect() protoreflect.Message {
	mi := &file_election_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionFailed.ProtoReflect.Descriptor instead.
func (*ElectionFailed) Descriptor() ([]byte, []int) {
	return file_election_proto_rawDescGZIP(), []int{2}
}

func (x *ElectionFailed) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *ElectionFailed) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ElectionFailed) GetClusterPath() string {
	if x != nil {
		return x.ClusterPath
	}
	return ""
}

func (x *ElectionFailed) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ElectionFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ElectionFailed) GetTimestampMicros() int64 {
	if x != nil {
		return x.TimestampMicros
	}
	return 0
}

// GroupClaim is broadcast by a node electing itself to host every member
// of a same-node CapsuleGroup. The semantics mirror Claim but the unit of
// election is the entire group: the combined-fit score covers all members,
// the listener is keyed on group_id, and the winning node alone starts
// every member in topological order.
//
// Tiebreak rules are identical to per-replica Claim:
//  1. Higher gravity_score wins.
//  2. Smaller offset_micros wins (deterministic priority delay; O14b).
//  3. Lexicographically smaller node_id wins.
type GroupClaim struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ClusterPath     string                 `protobuf:"bytes,2,opt,name=cluster_path,json=clusterPath,proto3" json:"cluster_path,omitempty"`
	NodeId          string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                             // Node claiming the group
	GravityScore    float64                `protobuf:"fixed64,4,opt,name=gravity_score,json=gravityScore,proto3" json:"gravity_score,omitempty"`         // Combined-fit score, 0–100
	TimestampMicros int64                  `protobuf:"varint,5,opt,name=timestamp_micros,json=timestampMicros,proto3" json:"timestamp_micros,omitempty"` // Claim creation time, microseconds since epoch (observability only; NOT the tiebreak)
	MemberIds       []string               `protobuf:"bytes,6,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`                    // Group members in topological order
	OffsetMicros    int64                  `protobuf:"varint,7,opt,name=offset_micros,json=offsetMicros,proto3" json:"offset_micros,omitempty"`          // Deterministic priority delay in microseconds; SMALLER wins the tiebreak (O14b)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupClaim) Reset() {
	*x = GroupClaim{}
	mi := &file_election_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupClaim) ProtoMessage() {}

func (x *GroupClaim) ProtoReflect() protoreflect.Message {
	mi := &file_election_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupClaim.ProtoReflect.Descriptor instead.
func (*GroupClaim) Descriptor() ([]byte, []int) {
	return file_election_proto_rawDescGZIP(), []int{3}
}

func (x *GroupClaim) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupClaim) GetClusterPath() string {
	if x != nil {
		return x.ClusterPath
	}
	return ""
}

func (x *GroupClaim) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GroupClaim) GetGravityScore() float64 {
	if x != nil {
		return x.GravityScore
	}
	return 0
}

func (x *GroupClaim) GetTimestampMicros() int64 {
	if x != nil {
		return x.TimestampMicros
	}
	return 0
}

func (x *GroupClaim) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *GroupClaim) GetOffsetMicros() int64 {
	if x != nil {
		return x.OffsetMicros
	}
	return 0
}

var File_election_proto protoreflect.FileDescriptor

const file_election_proto_rawDesc = "" +
	"\n" +
	"\x0eelection.proto\x12\x0efalak.election\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\x0fElectionMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xf6\x01\n" +
	"\x05Claim\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\tR\treplicaId\x12!\n" +
	"\fcluster_path\x18\x03 \x01(\tR\vclusterPath\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12#\n" +
	"\rgravity_score\x18\x05 \x01(\x01R\fgravityScore\x12)\n" +
	"\x10timestamp_micros\x18\x06 \x01(\x03R\x0ftimestampMicros\x12#\n" +
	"\roffset_micros\x18\a \x01(\x03R\foffsetMicros\"\xd1\x01\n" +
	"\x0eElectionFailed\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\tR\treplicaId\x12!\n" +
	"\fcluster_path\x18\x03 \x01(\tR\vclusterPath\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12)\n" +
	"\x10timestamp_micros\x18\x06 \x01(\x03R\x0ftimestampMicros\"\xf7\x01\n" +
	"\n" +
	"GroupClaim\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\fcluster_path\x18\x02 \x01(\tR\vclusterPath\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12#\n" +
	"\rgravity_score\x18\x04 \x01(\x01R\fgravityScore\x12)\n" +
	"\x10timestamp_micros\x18\x05 \x01(\x03R\x0ftimestampMicros\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x06 \x03(\tR\tmemberIds\x12#\n" +
	"\roffset_micros\x18\a \x01(\x03R\foffsetMicrosB7Z5github.com/tareksalem/falak/election/proto/electionpbb\x06proto3"

var (
	file_election_proto_rawDescOnce sync.Once
	file_election_proto_rawDescData []byte
)

func file_election_proto_rawDescGZIP() []byte {
	file_election_proto_rawDescOnce.Do(func() {
		file_election_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_election_proto_rawDesc), len(file_election_proto_rawDesc)))
	})
	return file_election_proto_rawDescData
}

var file_election_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_election_proto_goTypes = []any{
	(*ElectionMessage)(nil),       // 0: falak.election.ElectionMessage
	(*Claim)(nil),                 // 1: falak.election.Claim
	(*ElectionFailed)(nil),        // 2: falak.election.ElectionFailed
	(*GroupClaim)(nil),            // 3: falak.election.GroupClaim
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_election_proto_depIdxs = []int32{
	4, // 0: falak.election.ElectionMessage.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_election_proto_init() }
func file_election_proto_init() {
	if File_election_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_election_proto_rawDesc), len(file_election_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_election_proto_goTypes,
		DependencyIndexes: file_election_proto_depIdxs,
		MessageInfos:      file_election_proto_msgTypes,
	}.Build()
	File_election_proto = out.File
	file_election_proto_goTypes = nil
	file_election_proto_depIdxs = nil
}
