// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: endpoint.proto

package endpointpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EndpointRecord is a single replica's reachability announcement on the
// per-group endpoint topic. Multiple records may coexist for the same
// capsule (one per replica).
type EndpointRecord struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ClusterPath string                 `protobuf:"bytes,1,opt,name=cluster_path,json=clusterPath,proto3" json:"cluster_path,omitempty"`
	GroupId     string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CapsuleName string                 `protobuf:"bytes,3,opt,name=capsule_name,json=capsuleName,proto3" json:"capsule_name,omitempty"`
	ReplicaId   string                 `protobuf:"bytes,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	NodeId      string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BridgeIp    string                 `protobuf:"bytes,6,opt,name=bridge_ip,json=bridgeIp,proto3" json:"bridge_ip,omitempty"`
	NamedPorts  []*NamedPort           `protobuf:"bytes,7,rep,name=named_ports,json=namedPorts,proto3" json:"named_ports,omitempty"`
	// swim_state mirrors the publishing node's view of the replica:
	// "alive", "suspect", or "dead". Subscribers filter on this value.
	SwimState string                 `protobuf:"bytes,8,opt,name=swim_state,json=swimState,proto3" json:"swim_state,omitempty"`
	EmittedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	// ttl_seconds is the receiver hint: keep this record around for at
	// most TTL × 2 before treating it as expired.
	TtlSeconds    int32 `protobuf:"varint,10,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointRecord) Reset() {
	*x = EndpointRecord{}
	mi := &file_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointRecord) ProtoMessage() {}

func (x *EndpointRecord) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointRecord.ProtoReflect.Descriptor instead.
func (*EndpointRecord) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointRecord) GetClusterPath() string {
	if x != nil {
		return x.ClusterPath
	}
	return ""
}

func (x *EndpointRecord) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *EndpointRecord) GetCapsuleName() string {
	if x != nil {
		return x.CapsuleName
	}
	return ""
}

func (x *EndpointRecord) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *EndpointRecord) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EndpointRecord) GetBridgeIp() string {
	if x != nil {
		return x.BridgeIp
	}
	return ""
}

func (x *EndpointRecord) GetNamedPorts() []*NamedPort {
	if x != nil {
		return x.NamedPorts
	}
	return nil
}

func (x *EndpointRecord) GetSwimState() string {
	if x != nil {
		return x.SwimState
	}
	return ""
}

func (x *EndpointRecord) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *EndpointRecord) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// NamedPort maps a logical port name to its container-side numeric value
// and IP protocol. DNS resolution by name uses these entries.
type NamedPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContainerPort uint32                 `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	// protocol is "tcp" or "udp"; empty implies tcp.
	Protocol      string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedPort) Reset() {
	*x = NamedPort{}
	mi := &file_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedPort) ProtoMessage() {}

func (x *NamedPort) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedPort.ProtoReflect.Descriptor instead.
func (*NamedPort) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *NamedPort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedPort) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *NamedPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// EndpointWithdrawal removes an EndpointRecord for a specific replica.
// Used on graceful container stop; the receiver also expires records
// automatically via TTL when no withdrawal arrives.
type EndpointWithdrawal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterPath   string                 `protobuf:"bytes,1,opt,name=cluster_path,json=clusterPath,proto3" json:"cluster_path,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CapsuleName   string                 `protobuf:"bytes,3,opt,name=capsule_name,json=capsuleName,proto3" json:"capsule_name,omitempty"`
	ReplicaId     string                 `protobuf:"bytes,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EmittedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointWithdrawal) Reset() {
	*x = EndpointWithdrawal{}
	mi := &file_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointWithdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointWithdrawal) ProtoMessage() {}

func (x *EndpointWithdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointWithdrawal.ProtoReflect.Descriptor instead.
func (*EndpointWithdrawal) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointWithdrawal) GetClusterPath() string {
	if x != nil {
		return x.ClusterPath
	}
	return ""
}

func (x *EndpointWithdrawal) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *EndpointWithdrawal) GetCapsuleName() string {
	if x != nil {
		return x.CapsuleName
	}
	return ""
}

func (x *EndpointWithdrawal) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *EndpointWithdrawal) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EndpointWithdrawal) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

// Envelope wraps a record or withdrawal payload with a signature so
// receivers can verify the message came from the claimed sender. The
// sender's public key is looked up by node ID via the cluster phonebook.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is "record" or "withdrawal".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// payload is the marshalled EndpointRecord or EndpointWithdrawal.
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Envelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_endpoint_proto protoreflect.FileDescriptor

const file_endpoint_proto_rawDesc = "" +
	"\n" +
	"\x0eendpoint.proto\x12\rfalak.network\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x02\n" +
	"\x0eEndpointRecord\x12!\n" +
	"\fcluster_path\x18\x01 \x01(\tR\vclusterPath\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12!\n" +
	"\fcapsule_name\x18\x03 \x01(\tR\vcapsuleName\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\tR\treplicaId\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tbridge_ip\x18\x06 \x01(\tR\bbridgeIp\x129\n" +
	"\vnamed_ports\x18\a \x03(\v2\x18.falak.network.NamedPortR\n" +
	"namedPorts\x12\x1d\n" +
	"\n" +
	"swim_state\x18\b \x01(\tR\tswimState\x129\n" +
	"\n" +
	"emitted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12\x1f\n" +
	"\vttl_seconds\x18\n" +
	" \x01(\x05R\n" +
	"ttlSeconds\"b\n" +
	"\tNamedPort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\rR\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xe8\x01\n" +
	"\x12EndpointWithdrawal\x12!\n" +
	"\fcluster_path\x18\x01 \x01(\tR\vclusterPath\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12!\n" +
	"\fcapsule_name\x18\x03 \x01(\tR\vcapsuleName\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\tR\treplicaId\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"emitted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\"\xad\x01\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignatureB6Z4github.com/tareksalem/falak/network/proto/endpointpbb\x06proto3"

var (
	file_endpoint_proto_rawDescOnce sync.Once
	file_endpoint_proto_rawDescData []byte
)

func file_endpoint_proto_rawDescGZIP() []byte {
	file_endpoint_proto_rawDescOnce.Do(func() {
		file_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoint_proto_rawDesc), len(file_endpoint_proto_rawDesc)))
	})
	return file_endpoint_proto_rawDescData
}

var file_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_endpoint_proto_goTypes = []any{
	(*EndpointRecord)(nil),        // 0: falak.network.EndpointRecord
	(*NamedPort)(nil),             // 1: falak.network.NamedPort
	(*EndpointWithdrawal)(nil),    // 2: falak.network.EndpointWithdrawal
	(*Envelope)(nil),              // 3: falak.network.Envelope
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_endpoint_proto_depIdxs = []int32{
	1, // 0: falak.network.EndpointRecord.named_ports:type_name -> falak.network.NamedPort
	4, // 1: falak.network.EndpointRecord.emitted_at:type_name -> google.protobuf.Timestamp
	4, // 2: falak.network.EndpointWithdrawal.emitted_at:type_name -> google.protobuf.Timestamp
	4, // 3: falak.network.Envelope.timestamp:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_endpoint_proto_init() }
func file_endpoint_proto_init() {
	if File_endpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoint_proto_rawDesc), len(file_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoint_proto_goTypes,
		DependencyIndexes: file_endpoint_proto_depIdxs,
		MessageInfos:      file_endpoint_proto_msgTypes,
	}.Build()
	File_endpoint_proto = out.File
	file_endpoint_proto_goTypes = nil
	file_endpoint_proto_depIdxs = nil
}
